# Generated by Django 6.0.4 on 2026-04-17 18:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Foursome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_number", models.PositiveSmallIntegerField()),
                (
                    "pink_ball_order",
                    models.JSONField(
                        default=list,
                        help_text="Ordered list of player PKs for pink ball rotation.",
                    ),
                ),
                ("has_phantom", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["group_number"],
            },
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("total_rounds", models.PositiveSmallIntegerField(default=2)),
                (
                    "rounds_to_count",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="None = all rounds count. Set to N for best-N-of-M.",
                        null=True,
                    ),
                ),
                (
                    "active_games",
                    models.JSONField(
                        default=list,
                        help_text="List of GameType values active for this tournament.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChampionshipSeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seed_number", models.PositiveSmallIntegerField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.player"
                    ),
                ),
                (
                    "source_foursome",
                    models.ForeignKey(
                        help_text="The foursome this player won to earn their seed.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tournament.foursome",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchPlayChampionship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                            ("halved", "Halved"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "champion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="championships_won",
                        to="core.player",
                    ),
                ),
                (
                    "seeds",
                    models.ManyToManyField(
                        related_name="championship_seeds",
                        through="tournament.ChampionshipSeed",
                        to="core.player",
                    ),
                ),
                (
                    "tournament",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mp_championship",
                        to="tournament.tournament",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="championshipseed",
            name="championship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tournament.matchplaychampionship",
            ),
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.PositiveSmallIntegerField(default=1)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "active_games",
                    models.JSONField(
                        default=list,
                        help_text="List of GameType values active for this round.",
                    ),
                ),
                (
                    "bet_unit",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
                ),
                (
                    "scramble_config",
                    models.JSONField(
                        blank=True,
                        help_text="Config for scramble if active. Example: {'min_drives_per_player': 2, 'handicap_pct': 0.20}",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rounds",
                        to="core.course",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rounds",
                        to="tournament.tournament",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="foursome",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="foursomes",
                to="tournament.round",
            ),
        ),
        migrations.CreateModel(
            name="FoursomeMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_handicap",
                    models.SmallIntegerField(
                        help_text="Pre-calculated and stored at round setup."
                    ),
                ),
                (
                    "playing_handicap",
                    models.SmallIntegerField(
                        help_text="course_handicap adjusted by any local allowance (e.g. 90%)."
                    ),
                ),
                (
                    "foursome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tournament.foursome",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="core.player",
                    ),
                ),
                (
                    "tee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="core.tee",
                    ),
                ),
            ],
            options={
                "unique_together": {("foursome", "player")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="championshipseed",
            unique_together={("championship", "seed_number")},
        ),
        migrations.AlterUniqueTogether(
            name="foursome",
            unique_together={("round", "group_number")},
        ),
    ]
