# Generated by Django 6.0.4 on 2026-04-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_foursome_active_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foursome',
            name='active_games',
            field=models.JSONField(default=list, help_text='Games active for this specific foursome. When empty the round-level active_games applies.'),
        ),
    ]
