# Generated by Django 6.0.4 on 2026-04-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_foursomemembership_phantom_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foursomemembership',
            name='phantom_algorithm',
            field=models.CharField(default='rotating_player_scores', help_text='Algorithm id from scoring.phantom.REGISTRY.', max_length=50),
        ),
        migrations.AlterField(
            model_name='foursomemembership',
            name='phantom_config',
            field=models.JSONField(default=dict, help_text='Algorithm-specific config (e.g. rotation order).'),
        ),
    ]
