# Generated by Django 6.0.4 on 2026-05-05 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_ryder_cup_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tournamentteam',
            name='unique_team_number_per_tournament',
        ),
        migrations.AlterField(
            model_name='rydercupfoursomeconfig',
            name='game_type',
            field=models.CharField(choices=[('irish_rumble', 'Irish Rumble'), ('nassau', 'Nassau'), ('sixes', "Six's"), ('pink_ball', 'Pink Ball'), ('scramble', 'Scramble'), ('match_play', 'Match Play'), ('stableford', 'Stableford'), ('skins', 'Skins'), ('low_net_round', 'Low Net (Round)'), ('low_net', 'Low Net Championship'), ('points_531', 'Points 5-3-1'), ('three_person_match', 'Three-Person Match'), ('quota_nassau', 'Quota Nassau')], help_text='Game this foursome plays. Must be a GameType value supported by the app (nassau, quota_nassau, irish_rumble, match_play, etc.).', max_length=30),
        ),
        migrations.AlterField(
            model_name='rydercupmatchpoints',
            name='game_type',
            field=models.CharField(choices=[('irish_rumble', 'Irish Rumble'), ('nassau', 'Nassau'), ('sixes', "Six's"), ('pink_ball', 'Pink Ball'), ('scramble', 'Scramble'), ('match_play', 'Match Play'), ('stableford', 'Stableford'), ('skins', 'Skins'), ('low_net_round', 'Low Net (Round)'), ('low_net', 'Low Net Championship'), ('points_531', 'Points 5-3-1'), ('three_person_match', 'Three-Person Match'), ('quota_nassau', 'Quota Nassau')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rydercuproundconfig',
            name='point_multiplier',
            field=models.DecimalField(decimal_places=2, default='1.00', help_text='Multiplier applied to all points in this round. E.g. 2.0 makes every point worth double.', max_digits=5, validators=[django.core.validators.MinValueValidator('0.01')]),
        ),
        migrations.AlterField(
            model_name='teamtournament',
            name='cup_name',
            field=models.CharField(default='Ryder Cup', help_text="Display name for the team competition — e.g. 'Ryder Cup', 'Presidents Cup', 'Bandon Cup'. Shown in the app header and scoreboard.", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentteam',
            unique_together={('tournament', 'team_number')},
        ),
    ]
