# Generated by Django 6.0.4 on 2026-05-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_foursomeconfig_point_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rydercupfoursomeconfig',
            name='game_type',
            field=models.CharField(choices=[('irish_rumble', 'Irish Rumble'), ('nassau', 'Nassau'), ('sixes', "Six's"), ('pink_ball', 'Pink Ball'), ('scramble', 'Scramble'), ('match_play', 'Match Play'), ('stableford', 'Stableford'), ('skins', 'Skins'), ('low_net_round', 'Low Net (Round)'), ('low_net', 'Low Net Championship'), ('points_531', 'Points 5-3-1'), ('three_person_match', 'Three-Person Match'), ('quota_nassau', 'Quota Nassau'), ('singles', 'Singles')], help_text='Game this foursome plays. Must be a GameType value supported by the app (nassau, quota_nassau, irish_rumble, match_play, etc.).', max_length=30),
        ),
        migrations.AlterField(
            model_name='rydercupfoursomeconfig',
            name='point_value',
            field=models.DecimalField(decimal_places=2, default='1.00', help_text='Cup points awarded per match/segment win for this group.  Overrides the round-level nassau_point_value so that different game types can carry different weights (e.g. Fourball = 2 pts, Singles = 1 pt).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='rydercupmatchpoints',
            name='game_type',
            field=models.CharField(choices=[('irish_rumble', 'Irish Rumble'), ('nassau', 'Nassau'), ('sixes', "Six's"), ('pink_ball', 'Pink Ball'), ('scramble', 'Scramble'), ('match_play', 'Match Play'), ('stableford', 'Stableford'), ('skins', 'Skins'), ('low_net_round', 'Low Net (Round)'), ('low_net', 'Low Net Championship'), ('points_531', 'Points 5-3-1'), ('three_person_match', 'Three-Person Match'), ('quota_nassau', 'Quota Nassau'), ('singles', 'Singles')], max_length=30),
        ),
    ]
