# Generated by Django 6.0.4 on 2026-05-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_alter_rydercupfoursomeconfig_game_type_and_more'),
        ('tournament', '0014_round_game_point_values'),
    ]

    operations = [
    ]
