# Generated by Django 6.0.4 on 2026-05-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_merge_20260505_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='game_point_values',
            field=models.JSONField(blank=True, default=dict, help_text='Cup point value per game type, e.g. {"nassau": 1.0, "singles": 2.0}. Used only for Cup rounds. Stored at wizard time and applied per-foursome when the round is set up.'),
        ),
    ]
