# Generated by Django 6.0.4 on 2026-05-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_teamtournament_total_possible_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rydercupfoursomeconfig',
            name='game_type',
            field=models.CharField(choices=[('irish_rumble', 'Irish Rumble'), ('nassau', 'Nassau'), ('sixes', "Six's"), ('pink_ball', 'Pink Ball'), ('scramble', 'Scramble'), ('stableford', 'Stableford'), ('skins', 'Skins'), ('low_net_round', 'Low Net (Round)'), ('low_net', 'Low Net Championship'), ('points_531', 'Points 5-3-1'), ('three_person_match', 'Three-Person Match'), ('quota_nassau', 'Quota Nassau'), ('singles_nassau', 'Singles Nassau'), ('singles_18', '18-Hole Singles')], help_text='Game this foursome plays. Must be a GameType value supported by the app (nassau, quota_nassau, irish_rumble, match_play, etc.).', max_length=30),
        ),
        migrations.AlterField(
            model_name='rydercupmatchpoints',
            name='game_type',
            field=models.CharField(choices=[('irish_rumble', 'Irish Rumble'), ('nassau', 'Nassau'), ('sixes', "Six's"), ('pink_ball', 'Pink Ball'), ('scramble', 'Scramble'), ('stableford', 'Stableford'), ('skins', 'Skins'), ('low_net_round', 'Low Net (Round)'), ('low_net', 'Low Net Championship'), ('points_531', 'Points 5-3-1'), ('three_person_match', 'Three-Person Match'), ('quota_nassau', 'Quota Nassau'), ('singles_nassau', 'Singles Nassau'), ('singles_18', '18-Hole Singles')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rydercuproundconfig',
            name='format_declarations',
            field=models.JSONField(blank=True, help_text='Declared game formats for this round. Used to compute total_possible before foursomes are configured. See model docstring for format.', null=True),
        ),
    ]
