# Generated by Django 6.0.4 on 2026-05-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0021_round_cup_group_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='cup_group_counts',
            field=models.JSONField(blank=True, default=dict, help_text='Number of groups (foursomes) playing each game type in this cup round. Set at wizard time so total_possible can be computed before the round is configured. e.g. {"quota_nassau": 3} or {"irish_rumble": 2, "singles_nassau": 1}.'),
        ),
        migrations.AlterField(
            model_name='round',
            name='game_point_values',
            field=models.JSONField(blank=True, default=dict, help_text='Cup point value per game type, e.g. {"nassau": 1.0, "singles_nassau": 2.0}. Used only for Cup rounds. Stored at wizard time and applied per-foursome when the round is set up.'),
        ),
        migrations.AlterField(
            model_name='rydercuproundconfig',
            name='format_declarations',
            field=models.JSONField(blank=True, help_text='Declared game formats for this round. Used to compute total_possible before foursomes are configured. See model docstring for format.', null=True),
        ),
    ]
