# Generated by Django 6.0.4 on 2026-05-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0028_alter_rydercupfoursomeconfig_game_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rydercuproundconfig',
            name='round_format',
            field=models.CharField(choices=[('custom', 'Custom (per-foursome pick)'), ('triple_cup', 'One Day Ryder Cup (Triple Cup)')], default='custom', help_text="Preset that drives the per-foursome game type at setup time.  'triple_cup' forces every foursome to Triple Cup.", max_length=20),
        ),
    ]
