# Generated by Django 6.0.5 on 2026-06-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0033_alter_rydercupfoursomeconfig_game_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foursomemembership',
            name='is_scorer',
            field=models.BooleanField(default=False, help_text='This member scores for the foursome (delegated cross-account score entry).'),
        ),
    ]
