# Generated by Django 6.0.5 on 2026-06-06 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_catalogcourse_course_city_course_country_and_more'),
        ('tournament', '0034_foursomemembership_is_scorer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Normalized E.164.', max_length=32)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.player')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='tournament.round')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='tournament.tournament')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('round', 'phone'), name='uniq_round_watcher'), models.UniqueConstraint(fields=('tournament', 'phone'), name='uniq_tournament_watcher')],
            },
        ),
    ]
