# Generated by Django 6.0.5 on 2026-06-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0035_watcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='foursomemembership',
            name='withdrew_after_hole',
            field=models.SmallIntegerField(blank=True, help_text='Last hole this player completed before withdrawing; null = played the full round.', null=True),
        ),
        migrations.AddField(
            model_name='foursomemembership',
            name='withdrew_killed_next_hole',
            field=models.BooleanField(default=False, help_text='True if the hole after withdrawal was abandoned by the whole group (voided).'),
        ),
    ]
