# Generated by Django 6.0.5 on 2026-06-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0037_messagethread_message_threadread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rydercupfoursomeconfig',
            name='game_type',
            field=models.CharField(choices=[('irish_rumble', 'Irish Rumble'), ('nassau', 'Nassau'), ('sixes', 'Sixes'), ('pink_ball', 'Pink Ball'), ('scramble', 'Scramble'), ('stableford', 'Stableford'), ('skins', 'Skins'), ('multi_skins', 'Multi-Group Skins'), ('low_net_round', 'Low Net (Round)'), ('low_net', 'Low Net Championship'), ('points_531', 'Points 5-3-1'), ('three_person_match', 'Three-Person Match'), ('match_play', 'Match Play'), ('quota_nassau', 'Quota Nassau'), ('singles_nassau', 'Singles Nassau'), ('singles_18', '18-Hole Singles'), ('triple_cup', 'One-Round Triple Cup'), ('wolf', 'Wolf'), ('rabbit', 'Rabbit'), ('vegas', 'Las Vegas')], help_text='Game this foursome plays. Must be a GameType value supported by the app (nassau, quota_nassau, irish_rumble, match_play, etc.).', max_length=30),
        ),
        migrations.AlterField(
            model_name='rydercupmatchpoints',
            name='game_type',
            field=models.CharField(choices=[('irish_rumble', 'Irish Rumble'), ('nassau', 'Nassau'), ('sixes', 'Sixes'), ('pink_ball', 'Pink Ball'), ('scramble', 'Scramble'), ('stableford', 'Stableford'), ('skins', 'Skins'), ('multi_skins', 'Multi-Group Skins'), ('low_net_round', 'Low Net (Round)'), ('low_net', 'Low Net Championship'), ('points_531', 'Points 5-3-1'), ('three_person_match', 'Three-Person Match'), ('match_play', 'Match Play'), ('quota_nassau', 'Quota Nassau'), ('singles_nassau', 'Singles Nassau'), ('singles_18', '18-Hole Singles'), ('triple_cup', 'One-Round Triple Cup'), ('wolf', 'Wolf'), ('rabbit', 'Rabbit'), ('vegas', 'Las Vegas')], max_length=30),
        ),
    ]
