# Generated by Django 6.0.5 on 2026-06-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0038_alter_rydercupfoursomeconfig_game_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rydercupmatchpoints',
            name='segment',
            field=models.CharField(choices=[('front9', 'Front 9'), ('back9', 'Back 9'), ('overall', 'Overall 18'), ('fourball', 'Fourball'), ('foursomes', 'Foursomes'), ('singles', 'Singles')], max_length=10),
        ),
    ]
