# Generated by Django 6.0.5 on 2026-07-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0042_alter_rydercupfoursomeconfig_game_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foursome',
            name='name',
            field=models.CharField(blank=True, default='', help_text="Optional custom name for this group/foursome (e.g. a team name). Falls back to 'Group N' when blank — see display_name.", max_length=50),
        ),
    ]
