# Generated by Django 6.0.5 on 2026-07-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0043_foursome_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='primary_game',
            field=models.CharField(blank=True, help_text="The casual round's PRIMARY game — the one that owns score entry + configuration. Stored so the user's explicit pick survives (active_games is an unordered set; when two overlay games like Stroke Play + Skins are both present, which is primary can't be derived). Null = derive from active_games (tournament/legacy rounds).", max_length=40, null=True),
        ),
    ]
