# Generated by Django 6.0.5 on 2026-07-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0044_round_primary_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='foursome',
            name='shotgun_slot',
            field=models.CharField(blank=True, default='', help_text="Display-only tee-slot label (e.g. 'A'/'B') when multiple groups start on the same hole.", max_length=2),
        ),
        migrations.AddField(
            model_name='foursome',
            name='starting_hole',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Per-group shotgun start; null inherits the round's starting_hole.", null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='num_holes',
            field=models.PositiveSmallIntegerField(default=18, help_text='How many holes are played (e.g. 9 or 18).'),
        ),
        migrations.AddField(
            model_name='round',
            name='starting_hole',
            field=models.PositiveSmallIntegerField(default=1, help_text='Hole the round starts on (1 = normal). Foursome.starting_hole overrides per group for shotgun starts.'),
        ),
    ]
