# Generated by Django 6.0.4 on 2026-08-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0051_alter_rydercupfoursomeconfig_game_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='handicap_mode',
            field=models.CharField(choices=[('gross', 'Gross'), ('net', 'Net')], default='net', help_text='Individual play: field-wide handicap setting. The day-bet DQ reads this — a net event disqualifies the net money winners, a gross event the gross ones.', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='mini_singles_carve_pct',
            field=models.PositiveSmallIntegerField(default=0, help_text="Percent of the championship pool carved out for the Mini Singles day-2 champions' foursome. 0 = no carve-out."),
        ),
        migrations.AddField(
            model_name='tournament',
            name='net_percent',
            field=models.PositiveSmallIntegerField(default=100, help_text="Allowance applied when handicap_mode='net' (0–200)."),
        ),
        migrations.AddField(
            model_name='tournament',
            name='scoring_method',
            field=models.CharField(choices=[('stroke', 'Stroke play'), ('stableford', 'Stableford')], default='stroke', help_text='Individual play: how the championship is scored. One method, one board — a Stableford tournament does not also draw a net stroke board.', max_length=12),
        ),
    ]
