# Generated by Django 6.0.4 on 2026-08-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0052_tournament_handicap_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foursome',
            name='is_champions_foursome',
            field=models.BooleanField(default=False, help_text='Reserved for the Mini Singles day-2 champions. Filled from day 1, not by the TD.'),
        ),
    ]
