# Generated by Django 6.0.4 on 2026-08-22 20:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backfill_tee_curation_and_sync_version'),
        ('tournament', '0053_foursome_is_champions_foursome'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPlayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_format', models.CharField(choices=[('scramble', 'Scramble'), ('shamble', 'Shamble')], default='scramble', help_text='Scramble — all four hit, the best ball is played, ONE score per hole.  Shamble — best drive, then each man plays his own ball in, FOUR scores per hole.', max_length=10)),
                ('ball_count_mode', models.CharField(choices=[('fixed', 'Fixed'), ('escalating', 'Escalating — by sixes'), ('par_based', 'Par-based'), ('per_hole', 'Per hole')], default='fixed', help_text="Shamble only: how many of the four scores count on a hole. 'escalating' is a PRESET rather than a grid recipe — it is the shape people describe in words ('sixes'), and making them tap eighteen cells for it is the app failing to listen.", max_length=12)),
                ('ball_count_fixed', models.PositiveSmallIntegerField(default=2, help_text="Count used by ball_count_mode='fixed'. Best 2 of 4 is the default.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('ball_counts', models.JSONField(blank=True, default=dict, help_text="ball_count_mode='per_hole' only: {'1': 2, '2': 2, …} for holes 1-18.  A hole set to 4 is legal and flagged — no drop score, so one blow-up is the team's.")),
                ('drive_rule', models.CharField(choices=[('none', 'No requirement'), ('per_nine', 'Per nine'), ('per_eighteen', 'Per eighteen'), ('alternating', 'Alternating pairs')], default='none', help_text='Applies to BOTH formats — a shamble chooses a tee shot exactly as a scramble does.', max_length=12)),
                ('drives_required', models.PositiveSmallIntegerField(default=1, help_text="Quota rules only: drives owed per golfer per WINDOW (per nine, or per eighteen).  A short team owes four men's worth, not three — the phantom's share rotates through the three real men.")),
                ('drive_penalty', models.CharField(choices=[('warn', 'Warn only'), ('two_strokes', 'Two strokes per missing drive')], default='warn', help_text="Falling short costs NOTHING by default.  Two strokes per missing drive is opt-in and applied to the team's gross at the end of the round.  Silently disqualifying a team over a drive count would be the worst outcome the app could produce.  Does not apply to the alternating-pairs schedule — there is nothing to fall short of.", max_length=12)),
                ('handicap_mode', models.CharField(choices=[('net', 'Net'), ('gross', 'Gross')], default='net', help_text='Strokes-off-low needs a single opponent to anchor to and is not offered.', max_length=10)),
                ('allowance_override_pct', models.PositiveSmallIntegerField(blank=True, help_text="null = the format's table (scramble 25/20/15/10 lowest-first summed; shamble one percentage of each golfer's own, tracking the ball-count average).  Set to override with ONE flat percentage — a group's tradition beats the table.  The allowance is a table, not a preference: presenting it as an open question invites a guess.", null=True)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, help_text='Per golfer, flat, taken at signup. Stepped in $5 on screen — nobody charges $23.', max_digits=8)),
                ('places_paid', models.PositiveSmallIntegerField(default=3, help_text='Capped at the team count on screen.  Half the field cashing is ADVICE, not a rule — winner-takes-all is a legitimate preset.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('split_pcts', models.JSONField(blank=True, default=list, help_text="[50, 30, 20] — one entry per paid place, and it MUST total 100. A split adding to 95 leaves money in the TD's pocket with no line explaining it, so Save is blocked with the shortfall named in dollars.")),
                ('format_locked_at', models.DateTimeField(blank=True, help_text="Stamped by the first score.  Format and ball counts lock together: a one-number card cannot be re-read as four, and a hole scored under 'best 2' cannot be re-read as 'best 1'.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_play_config', to='tournament.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TeamPlayTeamState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(blank=True, help_text="Pine, Clay, Slate, Dune, Fern, Rust — the default team name and the row's identity.", max_length=20)),
                ('team_handicap', models.SmallIntegerField(blank=True, help_text='Whole strokes. Golfers do not play 6.15, and it looks like a spreadsheet error at the scoring table.', null=True)),
                ('team_handicap_raw', models.DecimalField(blank=True, decimal_places=2, help_text='The full-precision sum, shown UNDER the rounded figure so the TD sees where it came from.', max_digits=6, null=True)),
                ('drive_pairs', models.JSONField(blank=True, default=list, help_text='[[player_id, player_id], [player_id, player_id]] for four men; three men run AB / BC / AC repeating, stored as three pairs.  Immutable once written.')),
                ('drive_pairs_set_at', models.DateTimeField(blank=True, null=True)),
                ('foursome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_play_state', to='tournament.foursome')),
            ],
        ),
        migrations.CreateModel(
            name='TeamDrivePick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foursome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_drive_picks', to='tournament.foursome')),
                ('player', models.ForeignKey(help_text='The golfer whose drive was played. Never the phantom — the phantom has no tee shot.', on_delete=django.db.models.deletion.CASCADE, related_name='team_drives_used', to='core.player')),
            ],
            options={
                'ordering': ['hole_number'],
                'unique_together': {('foursome', 'hole_number')},
            },
        ),
    ]
