# Generated by Django 6.0.4 on 2026-08-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0054_teamplayconfig_teamplayteamstate_teamdrivepick'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayconfig',
            name='team_size',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Fours'), (2, 'Pairs')], default=4, help_text='Four or two.  It changes the format list on step 4 and the allowance table on step 6, and NOTHING else in the flow — same leaderboard, same payout, same settlement, same receipt.  Defaults to four, so every Foursome Play row reads unchanged.'),
        ),
        migrations.AddField(
            model_name='teamplayteamstate',
            name='name_is_default',
            field=models.BooleanField(default=True, help_text='False once the TD names the team himself, after which the roster may change without the name following it.'),
        ),
        migrations.AlterField(
            model_name='teamplayconfig',
            name='team_format',
            field=models.CharField(choices=[('scramble', 'Scramble'), ('shamble', 'Shamble'), ('best_ball', 'Best ball'), ('alternate_shot', 'Alternate shot'), ('scotch', 'Scotch'), ('chapman', 'Chapman')], default='scramble', help_text='Fours: scramble (all four hit, best ball played, ONE score a hole) or shamble (best drive, then each man plays his own ball in, FOUR scores a hole).  Pairs: scramble, best ball, alternate shot, Scotch or Chapman — four of the five end in one ball, and best ball is the only one entering two scores.', max_length=16),
        ),
    ]
