# Generated by Django 6.0.4 on 2026-08-23 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0055_pairs_play'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamplayteamstate',
            options={'ordering': ['foursome_id', 'slot']},
        ),
        migrations.AlterUniqueTogether(
            name='teamdrivepick',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='foursomemembership',
            name='team_play_slot',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 or 2 — which pair inside the playing group. Always 1 for a foursome event, where the group IS the team.'),
        ),
        migrations.AddField(
            model_name='teamdrivepick',
            name='slot',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='teamplayteamstate',
            name='name',
            field=models.CharField(blank=True, help_text='Pairs only — a foursome names itself through Foursome.name.', max_length=16),
        ),
        migrations.AddField(
            model_name='teamplayteamstate',
            name='slot',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 or 2 — which team inside the playing group. Always 1 for a foursome event, where the group IS the team.'),
        ),
        migrations.AlterField(
            model_name='teamplayteamstate',
            name='foursome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_play_states', to='tournament.foursome'),
        ),
        migrations.AlterUniqueTogether(
            name='teamdrivepick',
            unique_together={('foursome', 'slot', 'hole_number')},
        ),
        migrations.AlterUniqueTogether(
            name='teamplayteamstate',
            unique_together={('foursome', 'slot')},
        ),
    ]
