# Generated by Django 6.0.4 on 2026-08-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0056_alter_teamplayteamstate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamplayteamstate',
            name='name',
            field=models.CharField(blank=True, help_text='Pairs only — a foursome names itself through Foursome.name. Longer than the ball game\'s 16 because this one is not invented: it is two real surnames, and "Petersen & Reilly" is seventeen characters before anybody has typed anything.', max_length=32),
        ),
    ]
