# Generated by Django 6.0.4 on 2026-08-25 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0057_pair_name_width'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamplayconfig',
            name='drives_required',
            field=models.PositiveSmallIntegerField(default=1, help_text="Quota rules only: drives owed per golfer per WINDOW (per nine, or per eighteen).  A short team owes four golfers' worth, not three — the phantom's share rotates through the three real golfers."),
        ),
        migrations.AlterField(
            model_name='teamplayconfig',
            name='team_format',
            field=models.CharField(choices=[('scramble', 'Scramble'), ('shamble', 'Shamble'), ('best_ball', 'Best ball'), ('alternate_shot', 'Alternate shot'), ('scotch', 'Scotch'), ('chapman', 'Chapman')], default='scramble', help_text='Fours: scramble (all four hit, best ball played, ONE score a hole) or shamble (best drive, then each golfer plays their own ball in, FOUR scores a hole).  Pairs: scramble, best ball, alternate shot, Scotch or Chapman — four of the five end in one ball, and best ball is the only one entering two scores.', max_length=16),
        ),
        migrations.AlterField(
            model_name='teamplayteamstate',
            name='drive_pairs',
            field=models.JSONField(blank=True, default=list, help_text='[[player_id, player_id], [player_id, player_id]] for four golfers; three golfers run AB / BC / AC repeating, stored as three pairs.  Immutable once written.'),
        ),
        migrations.AlterField(
            model_name='teamplayteamstate',
            name='name_is_default',
            field=models.BooleanField(default=True, help_text='False once the TD names the team themselves, after which the roster may change without the name following it.'),
        ),
        migrations.CreateModel(
            name='LiveActivityToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Hex APNs token for this activity.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_activity_tokens', to='tournament.round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_activity_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('round', 'user')},
            },
        ),
    ]
