# Generated by Django 6.0.4 on 2026-08-30 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0059_settlementsend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementsend',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlement_sends', to='tournament.round'),
        ),
        migrations.AlterField(
            model_name='settlementsend',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlement_sends', to='tournament.tournament'),
        ),
        migrations.AddConstraint(
            model_name='settlementsend',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('round__isnull', True), ('tournament__isnull', False)), models.Q(('round__isnull', False), ('tournament__isnull', True)), _connector='OR'), name='settlementsend_exactly_one_parent'),
        ),
    ]
