# Generated by Django 6.0.4 on 2026-09-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0060_settlementsend_round_alter_settlementsend_tournament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveactivitytoken',
            name='token',
            field=models.TextField(help_text='Hex APNs token for this activity.'),
        ),
    ]
