# Generated by Django 6.0.4 on 2026-09-01 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0062_liveactivitystarttoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveActivityStartPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_activity_start_pushes', to='tournament.round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_activity_start_pushes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('round', 'user')},
            },
        ),
    ]
