# Generated by Django 6.0.4 on 2026-09-02 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tee_custom_index_of'),
        ('tournament', '0063_liveactivitystartpush'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementsend',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_sends', to='core.player'),
        ),
    ]
