# Generated by Django 6.0.4 on 2026-09-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0064_settlementsend_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='foursomemembership',
            name='playing_handicap_override',
            field=models.SmallIntegerField(blank=True, help_text='Forced playing handicap from an external card. Final — no allowance is applied on top. Null = computed.', null=True),
        ),
    ]
