# Generated by Django 6.0.4 on 2026-09-11 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_favoritegolfer'),
        ('tournament', '0068_alter_rydercupfoursomeconfig_game_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='flight_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of flights. 0 = unflighted (one board). Assignments are frozen in TournamentFlight.'),
        ),
        migrations.CreateModel(
            name='TournamentFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.PositiveSmallIntegerField(help_text='1 = the lowest-index flight.')),
                ('index_at_assignment', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_flights', to='core.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='tournament.tournament')),
            ],
            options={
                'ordering': ['flight', 'index_at_assignment'],
                'constraints': [models.UniqueConstraint(fields=('tournament', 'player'), name='unique_flight_per_tournament_player')],
            },
        ),
    ]
