# Generated by Django 6.0.4 on 2026-09-12 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0069_tournament_flight_count_tournamentflight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoursomeSetupUndo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField(default=dict)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('foursome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup_undo', to='tournament.foursome')),
            ],
        ),
    ]
