# Generated by Django 6.0.4 on 2026-09-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0070_foursomesetupundo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtournament',
            name='last_cup_push',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
