# Generated by Django 6.0.4 on 2026-09-30 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0075_alter_rydercupfoursomeconfig_game_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rydercuproundconfig',
            name='tc_alt_shot_high_pct',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Triple Cup alt-shot: % of the HIGHER partner's handicap. Blank = 50.", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='rydercuproundconfig',
            name='tc_alt_shot_low_pct',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Triple Cup alt-shot: % of the LOWER partner's handicap. Blank = 50.", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='rydercuproundconfig',
            name='tc_fourball_percent',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Triple Cup four-ball allowance %. Blank = the round's net %.", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='rydercuproundconfig',
            name='tc_singles_percent',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Triple Cup singles allowance %. Blank = the round's net %.", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
