# Generated by Django 6.0.4 on 2026-09-30 18:10

import django.core.validators
"""The Triple Cup allowances move from the ROUND to the CUP.

A multi-day cup plays the same allowances every day, so asking per round asked
the same question again and let two days of one cup disagree. One answer, on
the event.

**The order matters.** `makemigrations` puts the RemoveFields first, which
would drop the values before anything could move them; so the columns are
added, carried up, and only then removed. The per-round fields are a day old
and unreleased, so in practice there is nothing to carry — but a local event
configured while they existed would otherwise lose its settings silently,
which is the worst way to find out.
"""
from django.db import migrations, models


def carry_up_to_the_cup(apps, schema_editor):
    """First round that has an allowance set wins — they were meant to be the
    same on every round, and a cup with two different answers has no right
    one to pick."""
    RoundConfig = apps.get_model('tournament', 'RyderCupRoundConfig')
    FIELDS = ('tc_fourball_percent', 'tc_singles_percent',
              'tc_alt_shot_low_pct', 'tc_alt_shot_high_pct')
    for rc in RoundConfig.objects.all().order_by('round_id'):
        if all(getattr(rc, f) is None for f in FIELDS):
            continue
        tt = rc.tournament
        changed = False
        for f in FIELDS:
            v = getattr(rc, f)
            if v is not None and getattr(tt, f) is None:
                setattr(tt, f, v)
                changed = True
        if changed:
            tt.save(update_fields=list(FIELDS))


def back_down_to_every_round(apps, schema_editor):
    RoundConfig = apps.get_model('tournament', 'RyderCupRoundConfig')
    FIELDS = ('tc_fourball_percent', 'tc_singles_percent',
              'tc_alt_shot_low_pct', 'tc_alt_shot_high_pct')
    for rc in RoundConfig.objects.select_related('tournament').all():
        for f in FIELDS:
            setattr(rc, f, getattr(rc.tournament, f))
        rc.save(update_fields=list(FIELDS))


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0076_cup_triple_cup_allowances'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtournament',
            name='tc_alt_shot_high_pct',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Triple Cup alt-shot: % of the HIGHER partner's handicap. Blank = 50.", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='teamtournament',
            name='tc_alt_shot_low_pct',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Triple Cup alt-shot: % of the LOWER partner's handicap. Blank = 50.", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='teamtournament',
            name='tc_fourball_percent',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Triple Cup four-ball allowance %. Blank = the round's net %.", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='teamtournament',
            name='tc_singles_percent',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Triple Cup singles allowance %. Blank = the round's net %.", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.RunPython(carry_up_to_the_cup, back_down_to_every_round),
        migrations.RemoveField(
            model_name='rydercuproundconfig',
            name='tc_alt_shot_high_pct',
        ),
        migrations.RemoveField(
            model_name='rydercuproundconfig',
            name='tc_alt_shot_low_pct',
        ),
        migrations.RemoveField(
            model_name='rydercuproundconfig',
            name='tc_fourball_percent',
        ),
        migrations.RemoveField(
            model_name='rydercuproundconfig',
            name='tc_singles_percent',
        ),
    ]
