# Generated by Django 6.0.4 on 2026-08-27 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_user_discoverable_by_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('preview', 'Preview'), ('applied', 'Applied'), ('discarded', 'Discarded')], default='preview', max_length=10)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('header_line', models.PositiveIntegerField(default=0)),
                ('data_rows', models.PositiveIntegerField(default=0)),
                ('roster_size', models.PositiveIntegerField(default=0, help_text='Golfers already in the account when the file was read.')),
                ('parsed', models.JSONField(default=list)),
                ('overrides', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_runs', to='accounts.account')),
                ('user', models.ForeignKey(help_text='Who dropped the file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('account', 'number'), name='console_importrun_account_number_unique')],
            },
        ),
    ]
