# Generated by Django 6.0.4 on 2026-08-30 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_discoverable_by_name'),
        ('console', '0001_initial'),
        ('core', '0014_backfill_tee_curation_and_sync_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('verified', 'Checked, nothing wrong'), ('edited', 'Record corrected'), ('reported', 'Sent to Halved')], max_length=10)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('tee_name', models.CharField(blank=True, max_length=50)),
                ('changes', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, choices=[('scorecard', 'The printed scorecard'), ('ghin', 'GHIN'), ('club', 'The club told me')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('sent', 'Sent'), ('in_review', 'In review'), ('applied', 'Applied upstream')], max_length=10)),
                ('upstream', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_checks', to='accounts.account')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='core.course')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('account', 'number'), name='console_coursecheck_account_number_unique')],
            },
        ),
    ]
