[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn my_golf_app.wsgi --log-file -"
healthcheckPath = "/api/health/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
