# Generated by Django 6.0.4 on 2026-04-10 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('handicap_index', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(54)])),
                ('is_phantom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150)),
                ('tee_name', models.CharField(max_length=50)),
                ('slope', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(55), django.core.validators.MaxValueValidator(155)])),
                ('course_rating', models.DecimalField(decimal_places=1, max_digits=4)),
                ('par', models.PositiveSmallIntegerField(default=72)),
                ('holes', models.JSONField()),
            ],
        ),
    ]
