# Generated by Django 6.0.5 on 2026-06-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_account_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='golf_api_id',
            field=models.CharField(blank=True, db_index=True, help_text='Source GolfCourseAPI course id when imported from there; NULL for manual courses.', max_length=64, null=True),
        ),
    ]
