# Generated by Django 6.0.5 on 2026-06-05 15:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_golf_api_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golf_api_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='course',
            name='country',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='course',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='state',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='CatalogTee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tee_name', models.CharField(max_length=50)),
                ('slope', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(55), django.core.validators.MaxValueValidator(155)])),
                ('course_rating', models.DecimalField(decimal_places=1, max_digits=4)),
                ('par', models.PositiveSmallIntegerField(default=72)),
                ('holes', models.JSONField()),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('W', 'Female')], max_length=1, null=True)),
                ('default_sort_priority', models.PositiveSmallIntegerField(default=100)),
                ('catalog_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tees', to='core.catalogcourse')),
            ],
        ),
    ]
