# Generated by Django 6.0.5 on 2026-06-24 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_catalogcourse_course_city_course_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tee',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text='Replacement row when this tee was re-rated; null means this is the current revision.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='core.tee'),
        ),
    ]
