# Generated by Django 6.0.5 on 2026-07-03 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_gamesuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='home_course',
            field=models.ForeignKey(blank=True, help_text="Golfer's home course; pinned atop the course picker's default list.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.course'),
        ),
    ]
