# Generated by Django 6.0.5 on 2026-07-04 19:46

from django.db import migrations, models


def protect_existing_catalog(apps, schema_editor):
    """Everything currently in the catalog has been hand-vetted (imports were
    reviewed, ratings corrected, tees added by hand), so mark it all curated —
    a future API re-import then only ADDS new courses/tees and updates rows
    created fresh by the API, never overwriting today's work. Un-protect a
    specific course later with `manage.py mark_catalog_curated --uncurate`."""
    CatalogTee = apps.get_model('core', 'CatalogTee')
    CatalogTee.objects.update(curated=True, origin='manual')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_player_home_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogtee',
            name='curated',
            field=models.BooleanField(default=False, help_text='Human-vetted — protected from API re-import overwrite.'),
        ),
        migrations.AddField(
            model_name='catalogtee',
            name='origin',
            field=models.CharField(choices=[('api', 'GolfCourseAPI'), ('manual', 'Manual')], default='api', max_length=8),
        ),
        migrations.RunPython(protect_existing_catalog,
                             migrations.RunPython.noop),
    ]
