# Generated by Django 6.0.4 on 2026-07-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_player_ghin'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='phone_from_directory',
            field=models.BooleanField(default=False, help_text='Phone came from a name-search match rather than from the owner; never expose it.'),
        ),
    ]
