# Generated by Django 6.0.4 on 2026-08-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_player_phone_from_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogcourse',
            name='data_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='catalog_synced_version',
            field=models.PositiveIntegerField(default=0, help_text='Last CatalogCourse.data_version this account copy synced from; 0 = never.'),
        ),
        migrations.AddField(
            model_name='tee',
            name='curated',
            field=models.BooleanField(default=False, help_text='Deliberate local variant — protected from catalog re-sync overwrite/delete.'),
        ),
        migrations.AddField(
            model_name='tee',
            name='origin',
            field=models.CharField(choices=[('api', 'GolfCourseAPI'), ('manual', 'Manual')], default='api', max_length=8),
        ),
    ]
