# Generated by Django 6.0.4 on 2026-08-30 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backfill_tee_curation_and_sync_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='tee',
            name='custom_index_of',
            field=models.ForeignKey(blank=True, help_text='Source tee when this is a TD re-index; null for a normal tee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_index_sets', to='core.tee'),
        ),
    ]
