# Generated by Django 6.0.4 on 2026-09-05 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tee_custom_index_of'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteGolfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(help_text='The user whose shortlist this is.', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_golfers', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(help_text='The golfer on the shortlist.', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.player')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'player'), name='core_favoritegolfer_owner_player_unique')],
            },
        ),
    ]
