# Generated by Django 6.0.4 on 2026-05-22 21:01

import django.contrib.auth.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='accounts_user_account_username_unique',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists in this account.'}, help_text='150 characters or fewer.  Letters, digits and @/./+/-/_ only.  Unique within the account.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), models.F('account'), name='accounts_user_account_username_ci_unique'),
        ),
    ]
