# Generated by Django 6.0.5 on 2026-06-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_phone_user_phone_verified_at_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_code',
            field=models.CharField(blank=True, help_text='Stable per-user code for the public invite link /i/<code>/.', max_length=12, null=True, unique=True),
        ),
    ]
