# Generated by Django 6.0.5 on 2026-06-09 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_sentnotification_user_notification_prefs_devicetoken'),
        ('tournament', '0035_watcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_support',
            field=models.BooleanField(default=False, help_text="Halved support staff: READ-ONLY cross-account access to any round's leaderboard/scorecard for diagnosing reported issues. Does NOT grant write access. Every support lookup is logged (SupportAccessLog)."),
        ),
        migrations.CreateModel(
            name='SupportAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, help_text="Snapshot of the viewed account's name.", max_length=255)),
                ('query', models.CharField(blank=True, help_text='What support typed (watch token or round id).', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournament.round')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
