# Generated by Django 6.0.4 on 2026-07-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_is_support_supportaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discoverable_by_name',
            field=models.BooleanField(default=True, help_text='Findable by name when another member adds players to a round.  Phone lookup is unaffected.'),
        ),
    ]
