"""
accounts/management/commands/swap_to_accounts.py
------------------------------------------------
One-shot in-place migration from Django's built-in auth.User to our
custom accounts.User with multi-tenant Account scoping.

Django officially says swapping AUTH_USER_MODEL after the initial
migrations have run is "not supported" — it works fine on a fresh DB,
but an existing DB has all its FKs pointing at auth_user and Django's
migration framework has no path to rewrite them.  This command does
the rewrite directly in SQL, idempotently and inside a single
transaction so a mid-flight failure rolls back cleanly.

Usage
-----
    poetry run python manage.py swap_to_accounts \\
        --account-name "Golden Glove"

After it completes, `manage.py migrate` should report no pending
operations — the accounts.0001_initial migration is marked applied
manually with a timestamp that precedes admin.0001_initial so
Django's consistency check is satisfied.

The same command, with --account-name set to whatever you want the
production tenant to be called, is what you'll run on Railway when
you're ready to deploy the accounts branch.

Notes
-----
* IDs are preserved across the auth_user → accounts_user copy so the
  user_id FK columns on core_player and authtoken_token only need a
  retargeted constraint, not an id-value rewrite.
* All non-superuser flags are copied verbatim (last_login, email,
  date_joined, password hash, etc.).  Existing tokens keep working.
* is_account_admin is set True for any username in
  --admin-usernames (defaults to ("paul",)).  is_staff and
  is_superuser are kept from auth_user — we still want admin-site
  access for the same accounts.
* Group/permission M2M rows are copied over so contrib.admin keeps
  working unchanged.
* The command is idempotent: re-running it is a no-op once the swap
  is complete.
"""

from __future__ import annotations

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError
from django.db import connection, transaction


DEFAULT_ACCOUNT_NAME = 'Golden Glove'
DEFAULT_ADMIN_USERNAMES = ('paul',)


# DDL that mirrors what accounts.0001_initial would CREATE on a fresh
# DB.  Pulled from `manage.py sqlmigrate accounts 0001_initial` and
# wrapped in IF NOT EXISTS so the command can re-run safely.
CREATE_TABLES_SQL = [
    """
    CREATE TABLE IF NOT EXISTS "accounts_account" (
        "id"         bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "name"       varchar(80) NOT NULL,
        "created_at" timestamp with time zone NOT NULL
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS "accounts_user" (
        "id"                bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "password"          varchar(128) NOT NULL,
        "last_login"        timestamp with time zone NULL,
        "is_superuser"      boolean NOT NULL,
        "username"          varchar(150) NOT NULL UNIQUE,
        "first_name"        varchar(150) NOT NULL,
        "last_name"         varchar(150) NOT NULL,
        "email"             varchar(254) NOT NULL,
        "is_staff"          boolean NOT NULL,
        "is_active"         boolean NOT NULL,
        "date_joined"       timestamp with time zone NOT NULL,
        "is_account_admin"  boolean NOT NULL,
        "account_id"        bigint NOT NULL
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS "accounts_user_groups" (
        "id"       bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "user_id"  bigint NOT NULL,
        "group_id" integer NOT NULL
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS "accounts_user_user_permissions" (
        "id"            bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "user_id"       bigint NOT NULL,
        "permission_id" integer NOT NULL
    );
    """,
]


CREATE_INDEXES_AND_CONSTRAINTS_SQL = [
    # CI unique index on Account.name — uses LOWER() so case-insensitive
    # dedup works without storing a lowercased copy.
    """
    CREATE UNIQUE INDEX IF NOT EXISTS "accounts_account_name_ci_unique"
        ON "accounts_account" ((LOWER("name")));
    """,
    # accounts_user.account_id FK + UniqueConstraint(account, username)
    """
    DO $$ BEGIN
        ALTER TABLE "accounts_user"
            ADD CONSTRAINT "accounts_user_account_id_fk"
            FOREIGN KEY ("account_id") REFERENCES "accounts_account" ("id")
            DEFERRABLE INITIALLY DEFERRED;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END $$;
    """,
    """
    DO $$ BEGIN
        ALTER TABLE "accounts_user"
            ADD CONSTRAINT "accounts_user_account_username_unique"
            UNIQUE ("account_id", "username");
    EXCEPTION WHEN duplicate_object THEN NULL;
    END $$;
    """,
    """
    CREATE INDEX IF NOT EXISTS "accounts_user_username_like"
        ON "accounts_user" ("username" varchar_pattern_ops);
    """,
    """
    CREATE INDEX IF NOT EXISTS "accounts_user_account_id_idx"
        ON "accounts_user" ("account_id");
    """,
    # accounts_user_groups indexes / FKs
    """
    DO $$ BEGIN
        ALTER TABLE "accounts_user_groups"
            ADD CONSTRAINT "accounts_user_groups_user_group_uniq"
            UNIQUE ("user_id", "group_id");
    EXCEPTION WHEN duplicate_object THEN NULL;
    END $$;
    """,
    """
    DO $$ BEGIN
        ALTER TABLE "accounts_user_groups"
            ADD CONSTRAINT "accounts_user_groups_user_fk"
            FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id")
            DEFERRABLE INITIALLY DEFERRED;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END $$;
    """,
    """
    DO $$ BEGIN
        ALTER TABLE "accounts_user_groups"
            ADD CONSTRAINT "accounts_user_groups_group_fk"
            FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id")
            DEFERRABLE INITIALLY DEFERRED;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END $$;
    """,
    """
    CREATE INDEX IF NOT EXISTS "accounts_user_groups_user_idx"
        ON "accounts_user_groups" ("user_id");
    """,
    """
    CREATE INDEX IF NOT EXISTS "accounts_user_groups_group_idx"
        ON "accounts_user_groups" ("group_id");
    """,
    # accounts_user_user_permissions indexes / FKs
    """
    DO $$ BEGIN
        ALTER TABLE "accounts_user_user_permissions"
            ADD CONSTRAINT "accounts_user_perms_user_perm_uniq"
            UNIQUE ("user_id", "permission_id");
    EXCEPTION WHEN duplicate_object THEN NULL;
    END $$;
    """,
    """
    DO $$ BEGIN
        ALTER TABLE "accounts_user_user_permissions"
            ADD CONSTRAINT "accounts_user_perms_user_fk"
            FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id")
            DEFERRABLE INITIALLY DEFERRED;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END $$;
    """,
    """
    DO $$ BEGIN
        ALTER TABLE "accounts_user_user_permissions"
            ADD CONSTRAINT "accounts_user_perms_perm_fk"
            FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id")
            DEFERRABLE INITIALLY DEFERRED;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END $$;
    """,
    """
    CREATE INDEX IF NOT EXISTS "accounts_user_user_perms_user_idx"
        ON "accounts_user_user_permissions" ("user_id");
    """,
    """
    CREATE INDEX IF NOT EXISTS "accounts_user_user_perms_perm_idx"
        ON "accounts_user_user_permissions" ("permission_id");
    """,
]


class Command(BaseCommand):
    help = (
        'Migrate auth.User data to the new accounts.User table, '
        'creating a tenant Account and re-pointing all FKs.  '
        'Idempotent; safe to re-run.'
    )

    def add_arguments(self, parser):
        parser.add_argument(
            '--account-name',
            default=DEFAULT_ACCOUNT_NAME,
            help='Account name to create for the migrated users '
                 f'(default: {DEFAULT_ACCOUNT_NAME!r}).',
        )
        parser.add_argument(
            '--admin-usernames',
            nargs='+',
            default=list(DEFAULT_ADMIN_USERNAMES),
            help='Usernames flagged is_account_admin=True '
                 f'(default: {list(DEFAULT_ADMIN_USERNAMES)!r}).',
        )
        parser.add_argument(
            '--dry-run',
            action='store_true',
            help='Print what would happen without writing.',
        )

    @transaction.atomic
    def handle(self, *, account_name, admin_usernames, dry_run, **opts):
        if settings.AUTH_USER_MODEL != 'accounts.User':
            raise CommandError(
                "AUTH_USER_MODEL is not 'accounts.User' — switch the "
                "setting and add 'accounts' to INSTALLED_APPS first."
            )

        cur = connection.cursor()

        # ── 1. Inspect current state ──────────────────────────────────────────
        auth_user_exists  = self._table_exists(cur, 'auth_user')
        accounts_user_exists = self._table_exists(cur, 'accounts_user')

        if not auth_user_exists and accounts_user_exists:
            self.stdout.write(self.style.SUCCESS(
                'Swap already complete — auth_user is gone and '
                'accounts_user exists.  Nothing to do.'
            ))
            return

        if not auth_user_exists and not accounts_user_exists:
            raise CommandError(
                'Neither auth_user nor accounts_user exists.  This '
                'DB is in an unexpected state — run migrate on a '
                'fresh DB instead of using this command.'
            )

        # ── 2. Create the accounts_* tables (no-op if they exist) ─────────────
        self.stdout.write('Creating accounts_* tables...')
        for stmt in CREATE_TABLES_SQL + CREATE_INDEXES_AND_CONSTRAINTS_SQL:
            cur.execute(stmt)

        # ── 3. Bootstrap the Account ──────────────────────────────────────────
        cur.execute(
            'SELECT id FROM accounts_account WHERE LOWER(name) = LOWER(%s)',
            [account_name],
        )
        row = cur.fetchone()
        if row:
            account_id = row[0]
            self.stdout.write(
                f'  Account {account_name!r} already exists (id={account_id}).'
            )
        else:
            cur.execute(
                'INSERT INTO accounts_account ("name", "created_at") '
                'VALUES (%s, NOW()) RETURNING id',
                [account_name],
            )
            account_id = cur.fetchone()[0]
            self.stdout.write(
                f'  Created Account {account_name!r} (id={account_id}).'
            )

        # ── 4. Copy auth_user → accounts_user (preserving ids) ────────────────
        self.stdout.write('Copying users...')
        cur.execute("""
            INSERT INTO accounts_user (
                id, password, last_login, is_superuser, username,
                first_name, last_name, email, is_staff, is_active,
                date_joined, is_account_admin, account_id
            )
            SELECT
                u.id, u.password, u.last_login, u.is_superuser, u.username,
                u.first_name, u.last_name, u.email, u.is_staff, u.is_active,
                u.date_joined,
                CASE WHEN u.username = ANY(%s) THEN TRUE ELSE FALSE END
                    AS is_account_admin,
                %s AS account_id
            FROM auth_user u
            WHERE NOT EXISTS (
                SELECT 1 FROM accounts_user au WHERE au.id = u.id
            )
        """, [list(admin_usernames), account_id])
        copied = cur.rowcount
        self.stdout.write(f'  Copied {copied} user(s).')

        # Sync sequence so future INSERT ... DEFAULT picks up where we left off.
        cur.execute("""
            SELECT setval(
                pg_get_serial_sequence('accounts_user', 'id'),
                COALESCE((SELECT MAX(id) FROM accounts_user), 1),
                (SELECT MAX(id) IS NOT NULL FROM accounts_user)
            )
        """)

        # ── 5. Copy group / permission M2M rows ───────────────────────────────
        cur.execute("""
            INSERT INTO accounts_user_groups (user_id, group_id)
            SELECT user_id, group_id FROM auth_user_groups
            ON CONFLICT (user_id, group_id) DO NOTHING
        """)
        cur.execute("""
            INSERT INTO accounts_user_user_permissions (user_id, permission_id)
            SELECT user_id, permission_id FROM auth_user_user_permissions
            ON CONFLICT (user_id, permission_id) DO NOTHING
        """)

        # ── 6. Re-point Player.user FK from auth_user → accounts_user ────────
        self.stdout.write('Re-pointing FK references...')
        self._repoint_fk(
            cur,
            table='core_player',
            column='user_id',
            new_target_table='accounts_user',
            new_constraint='core_player_user_id_fk_accounts_user',
        )

        # ── 7. Re-point authtoken_token.user FK if the table exists ──────────
        if self._table_exists(cur, 'authtoken_token'):
            self._repoint_fk(
                cur,
                table='authtoken_token',
                column='user_id',
                new_target_table='accounts_user',
                new_constraint='authtoken_token_user_id_fk_accounts_user',
            )

        # ── 8. Drop the old auth_user tables ─────────────────────────────────
        self.stdout.write('Dropping auth_user tables...')
        cur.execute('DROP TABLE IF EXISTS auth_user_groups CASCADE')
        cur.execute('DROP TABLE IF EXISTS auth_user_user_permissions CASCADE')
        cur.execute('DROP TABLE IF EXISTS auth_user CASCADE')

        # ── 9. Mark accounts.0001_initial applied (before admin.0001) ────────
        self.stdout.write('Marking accounts.0001_initial as applied...')
        cur.execute("""
            SELECT applied FROM django_migrations
            WHERE app='admin' AND name='0001_initial'
        """)
        row = cur.fetchone()
        admin_applied = row[0] if row else None

        if admin_applied is None:
            raise CommandError(
                'admin.0001_initial is not in django_migrations — DB '
                'is in an unexpected state.'
            )

        cur.execute("""
            INSERT INTO django_migrations (app, name, applied)
            VALUES ('accounts', '0001_initial', %s)
            ON CONFLICT DO NOTHING
        """, [admin_applied - __import__('datetime').timedelta(microseconds=1)])

        if dry_run:
            self.stdout.write(self.style.WARNING(
                '\n--dry-run requested — rolling back.'
            ))
            transaction.set_rollback(True)
            return

        self.stdout.write(self.style.SUCCESS(
            f'\nDone.  Account {account_name!r} owns {copied} user(s).  '
            f'Admins: {sorted(admin_usernames)}.  '
            'Run `manage.py migrate` next to confirm consistency.'
        ))

    # ─────────────────────────────────────────────────────────────────────────

    def _table_exists(self, cur, name: str) -> bool:
        cur.execute("""
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = current_schema() AND table_name = %s
        """, [name])
        return cur.fetchone() is not None

    def _repoint_fk(self, cur, *, table: str, column: str,
                    new_target_table: str, new_constraint: str) -> None:
        """
        Drop every FK constraint on `table.column` (most likely pointing at
        auth_user.id) and recreate one pointing at `new_target_table.id`.
        """
        cur.execute("""
            SELECT conname
            FROM pg_constraint c
            JOIN pg_class t ON t.oid = c.conrelid
            JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ANY(c.conkey)
            WHERE c.contype = 'f'
              AND t.relname = %s
              AND a.attname = %s
        """, [table, column])
        existing = [r[0] for r in cur.fetchall()]
        for name in existing:
            cur.execute(f'ALTER TABLE "{table}" DROP CONSTRAINT "{name}"')
            self.stdout.write(f'  Dropped FK {name}.')

        cur.execute(f"""
            ALTER TABLE "{table}"
            ADD CONSTRAINT "{new_constraint}"
            FOREIGN KEY ("{column}") REFERENCES "{new_target_table}" ("id")
            DEFERRABLE INITIALLY DEFERRED
        """)
        self.stdout.write(
            f'  Re-pointed {table}.{column} → {new_target_table}.id.'
        )
