# Generated by Django 6.0.4 on 2026-04-10 20:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoleScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)])),
                ('gross_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('handicap_strokes', models.PositiveSmallIntegerField(default=0)),
                ('net_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stableford_points', models.SmallIntegerField(blank=True, null=True)),
                ('foursome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_scores', to='tournament.foursome')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hole_scores', to='core.player')),
            ],
            options={
                'ordering': ['hole_number'],
                'unique_together': {('foursome', 'player', 'hole_number')},
            },
        ),
        migrations.CreateModel(
            name='LowNetResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_scores', models.JSONField(default=list)),
                ('counted_scores', models.JSONField(default=list)),
                ('final_net', models.SmallIntegerField(blank=True, null=True)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='low_net_results', to='core.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_net_results', to='tournament.tournament')),
            ],
            options={
                'ordering': ['final_net'],
                'unique_together': {('tournament', 'player')},
            },
        ),
        migrations.CreateModel(
            name='SkinsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)])),
                ('skins_value', models.PositiveSmallIntegerField(default=1)),
                ('is_carryover', models.BooleanField(default=False)),
                ('foursome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skins_results', to='tournament.foursome')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skins_won', to='core.player')),
            ],
            options={
                'ordering': ['hole_number'],
                'unique_together': {('foursome', 'hole_number')},
            },
        ),
        migrations.CreateModel(
            name='StablefordResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.SmallIntegerField(default=0)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stableford_results', to='core.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stableford_results', to='tournament.round')),
            ],
            options={
                'ordering': ['-total_points'],
                'unique_together': {('round', 'player')},
            },
        ),
    ]
