# Generated by Django 6.0.4 on 2026-04-11 18:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_player_user'),
        ('scoring', '0001_initial'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinsResultNoCarryover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)])),
                ('skins_value', models.PositiveSmallIntegerField(default=1)),
                ('is_carryover', models.BooleanField(default=False)),
                ('foursome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skins_results_no_carryover', to='tournament.foursome')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skins_results_no_carryover', to='core.player')),
            ],
            options={
                'ordering': ['hole_number'],
                'unique_together': {('foursome', 'hole_number')},
            },
        ),
    ]
