# Generated by Django 6.0.4 on 2026-04-10 20:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrishRumbleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segments', models.JSONField(help_text='List of segment dicts with start_hole, end_hole, balls_to_count.')),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='irish_rumble_config', to='tournament.round')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracket_type', models.CharField(choices=[('single_elim', 'Single Elimination'), ('three_player_points', '3-Player Points')], max_length=25)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('halved', 'Halved')], default='pending', max_length=20)),
                ('foursome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_play_brackets', to='tournament.foursome')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_play_wins', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('start_hole', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('halved', 'Halved')], default='pending', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('player1', 'Player 1'), ('player2', 'Player 2'), ('halved', 'Halved')], max_length=10, null=True)),
                ('finished_on_hole', models.PositiveSmallIntegerField(blank=True, help_text='Hole number the match was conceded/won (for early finish tracking).', null=True)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='games.matchplaybracket')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mp_matches_as_p1', to='core.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mp_matches_as_p2', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='NassauSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_number', models.PositiveSmallIntegerField()),
                ('start_hole', models.PositiveSmallIntegerField()),
                ('end_hole', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('halved', 'Halved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foursome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nassau_segments', to='tournament.foursome')),
            ],
            options={
                'ordering': ['segment_number', 'start_hole'],
            },
        ),
        migrations.CreateModel(
            name='NassauTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.PositiveSmallIntegerField()),
                ('team_select_method', models.CharField(choices=[('long_drive', 'Long Drive'), ('coin_flip', 'Coin Flip'), ('remainder', 'Remainder')], max_length=20)),
                ('is_winner', models.BooleanField(default=False)),
                ('players', models.ManyToManyField(related_name='nassau_teams', to='core.player')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='games.nassausegment')),
            ],
        ),
        migrations.CreateModel(
            name='IrishRumbleSegmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_index', models.PositiveSmallIntegerField()),
                ('balls_counted', models.PositiveSmallIntegerField()),
                ('total_net_score', models.SmallIntegerField(blank=True, null=True)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('foursome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irish_rumble_results', to='tournament.foursome')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irish_rumble_results', to='tournament.round')),
            ],
            options={
                'unique_together': {('round', 'foursome', 'segment_index')},
            },
        ),
        migrations.CreateModel(
            name='MatchPlayHoleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.PositiveSmallIntegerField()),
                ('p1_net', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('p2_net', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('holes_up_after', models.SmallIntegerField(default=0)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mp_holes_won', to='core.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_results', to='games.matchplaymatch')),
            ],
            options={
                'ordering': ['hole_number'],
                'unique_together': {('match', 'hole_number')},
            },
        ),
        migrations.CreateModel(
            name='NassauHoleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.PositiveSmallIntegerField()),
                ('team1_best_net', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('team2_best_net', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_results', to='games.nassausegment')),
                ('winning_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holes_won', to='games.nassauteam')),
            ],
            options={
                'unique_together': {('segment', 'hole_number')},
            },
        ),
        migrations.CreateModel(
            name='PinkBallHoleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)])),
                ('net_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('foursome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pink_ball_results', to='tournament.foursome')),
                ('pink_ball_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pink_ball_holes', to='core.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pink_ball_results', to='tournament.round')),
            ],
            options={
                'ordering': ['hole_number'],
                'unique_together': {('round', 'foursome', 'hole_number')},
            },
        ),
        migrations.CreateModel(
            name='ScrambleHoleScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)])),
                ('gross_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('handicap_strokes', models.PositiveSmallIntegerField(default=0)),
                ('net_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('chosen_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scramble_drives_used', to='core.player')),
                ('foursome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scramble_scores', to='tournament.foursome')),
            ],
            options={
                'ordering': ['hole_number'],
                'unique_together': {('foursome', 'hole_number')},
            },
        ),
        migrations.CreateModel(
            name='ScrambleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_gross', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_net', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('drives_used', models.JSONField(default=dict)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('foursome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scramble_result', to='tournament.foursome')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scramble_results', to='tournament.round')),
            ],
            options={
                'unique_together': {('round', 'foursome')},
            },
        ),
    ]
