# Generated by Django 6.0.4 on 2026-04-11 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinkballholeresult',
            name='ball_lost',
            field=models.BooleanField(default=False, help_text='True if the physical ball was lost on this hole, eliminating this foursome.'),
        ),
        migrations.CreateModel(
            name='PinkBallResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminated_on_hole', models.PositiveSmallIntegerField(blank=True, help_text='Hole where ball was lost. Null = survived all 18.', null=True)),
                ('total_net_score', models.SmallIntegerField(blank=True, null=True)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('foursome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pink_ball_round_result', to='tournament.foursome')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pink_ball_round_results', to='tournament.round')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('round', 'foursome')},
            },
        ),
    ]
