# Generated by Django 6.0.4 on 2026-04-19 19:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("games", "0002_sixes_handicap_mode"),
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchPlay18Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "handicap_mode",
                    models.CharField(
                        choices=[
                            ("net", "Net"),
                            ("gross", "Gross"),
                            ("strokes_off", "Strokes Off Low"),
                        ],
                        default="net",
                        max_length=20,
                    ),
                ),
                ("net_percent", models.PositiveSmallIntegerField(default=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                            ("halved", "Halved"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("team1", "Team 1"),
                            ("team2", "Team 2"),
                            ("halved", "Halved"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "finished_on_hole",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Hole number the match was won (for early finish tracking).",
                        null=True,
                    ),
                ),
                (
                    "foursome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_play_18_games",
                        to="tournament.foursome",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchPlay18HoleResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hole_number",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(18),
                        ]
                    ),
                ),
                ("team1_best_net", models.SmallIntegerField(blank=True, null=True)),
                ("team2_best_net", models.SmallIntegerField(blank=True, null=True)),
                (
                    "winner",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("team1", "Team 1"),
                            ("team2", "Team 2"),
                            ("halved", "Halved"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("holes_up_after", models.SmallIntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hole_results",
                        to="games.matchplay18game",
                    ),
                ),
            ],
            options={
                "ordering": ["hole_number"],
                "unique_together": {("game", "hole_number")},
            },
        ),
        migrations.CreateModel(
            name="MatchPlay18Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_number",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ]
                    ),
                ),
                (
                    "team_select_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("long_drive", "Long Drive"),
                            ("random", "Random"),
                            ("remainder", "Remainder"),
                            ("loser_choice", "Loser's Choice"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="games.matchplay18game",
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        related_name="match_play_18_teams", to="core.player"
                    ),
                ),
            ],
            options={
                "unique_together": {("game", "team_number")},
            },
        ),
    ]
