# Generated by Django 6.0.4 on 2026-04-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_skins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points531game',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='points531playerholeresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skinsgame',
            name='allow_junk',
            field=models.BooleanField(default=False, help_text='If True the entry screen shows a per-player junk-skin counter (birdies, sandies, chip-ins, etc.).'),
        ),
        migrations.AlterField(
            model_name='skinsgame',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skinsholeresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skinsplayerholeresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skinsplayerholeresult',
            name='junk_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of junk skins (birdies, sandies, etc.) earned by this player on this hole.'),
        ),
    ]
