# Generated by Django 6.0.4 on 2026-04-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_lownet_championship_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irishrumbleconfig',
            name='payouts',
            field=models.JSONField(default=list, help_text="Payout per finishing place. Example: [{'place': 1, 'amount': 60.00}, {'place': 2, 'amount': 30.00}]"),
        ),
        migrations.AlterField(
            model_name='lownetchampionshipconfig',
            name='handicap_mode',
            field=models.CharField(choices=[('net', 'Net'), ('gross', 'Gross'), ('strokes_off', 'Strokes Off Low')], default='net', max_length=20),
        ),
        migrations.AlterField(
            model_name='pinkballconfig',
            name='payouts',
            field=models.JSONField(default=list, help_text="Payout per finishing place. Example: [{'place': 1, 'amount': 60.00}, {'place': 2, 'amount': 30.00}]"),
        ),
    ]
