# Generated by Django 6.0.4 on 2026-04-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_lownet_excluded_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lownetroundconfig',
            name='excluded_player_ids',
            field=models.JSONField(default=list, help_text='Player IDs excluded from prize payouts. Excluded players still appear in standings so their score is visible, but they receive no payout.'),
        ),
    ]
