# Generated by Django 6.0.4 on 2026-04-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_three_person_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threepersonmatch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='threepersonmatchp1holeresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='threepersonmatchp2holeresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='threepersonmatchp2holeresult',
            name='main_opp_net',
            field=models.SmallIntegerField(blank=True, help_text="During tiebreak: min(tied_a_net, tied_b_net). During phase2: runner_up's net score.", null=True),
        ),
    ]
