# Generated by Django 6.0.4 on 2026-04-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_alter_threepersonmatch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threepersonmatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='pending', max_length=20),
        ),
    ]
