# Generated by Django 6.0.4 on 2026-05-05 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_player_short_name'),
        ('games', '0021_quota_nassau'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quotanassauholeresult',
            name='unique_quota_hole_per_match',
        ),
        migrations.RemoveConstraint(
            model_name='quotanassaumatch',
            name='unique_quota_match_pairing',
        ),
        migrations.AlterUniqueTogether(
            name='quotanassauholeresult',
            unique_together={('match', 'hole_number')},
        ),
        migrations.AlterUniqueTogether(
            name='quotanassaumatch',
            unique_together={('game', 'player1', 'player2')},
        ),
    ]
