# Generated by Django 6.0.4 on 2026-05-17 01:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_player_short_name'),
        ('games', '0022_remove_quotanassauholeresult_unique_quota_hole_per_match_and_more'),
        ('tournament', '0025_multi_skins'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiSkinsGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('halved', 'Halved')], default='pending', max_length=20)),
                ('handicap_mode', models.CharField(choices=[('net', 'Net'), ('gross', 'Gross'), ('strokes_off', 'Strokes Off Low')], default='net', help_text='How per-hole scores are adjusted for ranking.', max_length=20)),
                ('net_percent', models.PositiveSmallIntegerField(default=100, help_text="Percentage of playing handicap applied when handicap_mode='net'.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('bet_unit', models.DecimalField(decimal_places=2, default=10.0, help_text='Dollar entry fee per participating player.', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(help_text='Players who paid into this pool. A player may belong to any foursome in this round.', related_name='multi_skins_games', to='core.player')),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multi_skins_game', to='tournament.round')),
            ],
        ),
        migrations.CreateModel(
            name='MultiSkinsHoleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_results', to='games.multiskinsgame')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multi_skins_holes_won', to='core.player')),
            ],
            options={
                'ordering': ['hole_number'],
                'unique_together': {('game', 'hole_number')},
            },
        ),
    ]
