# Generated by hand for the One-Round Ryder Cup ("Triple Cup") game.

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_player_short_name'),
        ('games', '0023_multi_skins'),
        ('tournament', '0027_account_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripleCupGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('halved', 'Halved')], default='pending', max_length=20)),
                ('handicap_mode', models.CharField(choices=[('net', 'Net'), ('gross', 'Gross'), ('strokes_off', 'Strokes Off Low')], default='net', help_text='How per-hole scores are adjusted for ranking.', max_length=20)),
                ('net_percent', models.PositiveSmallIntegerField(default=100, help_text="Percentage of playing handicap applied when handicap_mode='net'.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('alt_shot_low_pct', models.PositiveSmallIntegerField(default=50, help_text="% of the lower partner's handicap used in foursomes (alt-shot).", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('alt_shot_high_pct', models.PositiveSmallIntegerField(default=50, help_text="% of the higher partner's handicap used in foursomes (alt-shot).", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('phantom_score_mode', models.CharField(choices=[('net_par', 'Phantom plays net par on every hole'), ('net_bogey', 'Phantom plays net bogey on every hole')], default='net_par', help_text='Score the phantom partner posts in 2v1 fourball.', max_length=20)),
                ('group_size', models.PositiveSmallIntegerField(default=4, help_text='Real-player count at setup: 2, 3, or 4.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foursome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triple_cup_game', to='tournament.foursome')),
            ],
        ),
        migrations.CreateModel(
            name='TripleCupMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveSmallIntegerField(help_text='1..4 within the game.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('segment', models.CharField(choices=[('fourball', 'Fourball'), ('foursomes', 'Foursomes (Alt-Shot)'), ('singles', 'Singles')], max_length=20)),
                ('label', models.CharField(blank=True, help_text="Display label e.g. 'Singles 1' or 'Match 2'.", max_length=40)),
                ('start_hole', models.PositiveSmallIntegerField()),
                ('end_hole', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('halved', 'Halved')], default='pending', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('team1', 'Team 1'), ('team2', 'Team 2'), ('halved', 'Halved')], help_text='Set when match is decided.', max_length=10, null=True)),
                ('holes_up_after_final', models.SmallIntegerField(default=0, help_text='Final margin: +ve = team1 won, -ve = team2.')),
                ('finished_on_hole', models.PositiveSmallIntegerField(blank=True, help_text='Hole where the match was mathematically clinched.', null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='games.triplecupgame')),
            ],
            options={
                'ordering': ['match_number'],
                'unique_together': {('game', 'match_number')},
            },
        ),
        migrations.CreateModel(
            name='TripleCupTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.PositiveSmallIntegerField()),
                ('is_winner', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='games.triplecupmatch')),
                ('players', models.ManyToManyField(related_name='triple_cup_teams', to='core.player')),
            ],
            options={
                'ordering': ['team_number'],
                'unique_together': {('match', 'team_number')},
            },
        ),
        migrations.CreateModel(
            name='TripleCupHoleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)])),
                ('team1_net', models.SmallIntegerField(blank=True, null=True)),
                ('team2_net', models.SmallIntegerField(blank=True, null=True)),
                ('winning_team_number', models.PositiveSmallIntegerField(blank=True, help_text='1, 2, or null on halve.', null=True)),
                ('holes_up_after', models.SmallIntegerField(default=0, help_text='Running margin after this hole: +ve = team1 leading.')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_results', to='games.triplecupmatch')),
            ],
            options={
                'ordering': ['hole_number'],
                'unique_together': {('match', 'hole_number')},
            },
        ),
    ]
