# Generated by Django 6.0.4 on 2026-05-23 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_triple_cup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triplecupgame',
            name='phantom_score_mode',
        ),
    ]
