# Generated by Django 6.0.4 on 2026-05-24 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_account_fk'),
        ('games', '0025_remove_triplecupgame_phantom_score_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='triplecupmatch',
            name='team1_first_tee_player',
            field=models.ForeignKey(blank=True, help_text='Foursomes only: team1 player who tees off the first segment hole.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.player'),
        ),
        migrations.AddField(
            model_name='triplecupmatch',
            name='team2_first_tee_player',
            field=models.ForeignKey(blank=True, help_text='Foursomes only: team2 player who tees off the first segment hole.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.player'),
        ),
    ]
