# Generated by Django 6.0.4 on 2026-05-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0026_triplecupmatch_team1_first_tee_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplaybracket',
            name='handicap_mode',
            field=models.CharField(choices=[('net', 'Net'), ('gross', 'Gross'), ('strokes_off', 'Strokes Off Low')], default='net', help_text='Per-bracket handicap mode (net/gross/strokes_off).', max_length=20),
        ),
        migrations.AddField(
            model_name='matchplaybracket',
            name='net_percent',
            field=models.PositiveSmallIntegerField(default=100, help_text='Percentage of handicap applied when mode=net (0–200).'),
        ),
    ]
