# Generated by Django 6.0.4 on 2026-05-31 22:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_account_fk'),
        ('games', '0029_sixes_high_low'),
        ('tournament', '0032_alter_rydercupfoursomeconfig_game_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sixesholeresult',
            name='holes_up_after',
            field=models.SmallIntegerField(default=0, help_text='Running point margin after this hole: +ve = team1 leading.'),
        ),
        migrations.CreateModel(
            name='WolfGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('halved', 'Halved')], default='pending', max_length=20)),
                ('handicap_mode', models.CharField(choices=[('net', 'Net'), ('gross', 'Gross'), ('strokes_off', 'Strokes Off Low')], default='net', help_text='How per-hole scores are adjusted for ranking.', max_length=20)),
                ('net_percent', models.PositiveSmallIntegerField(default=100, help_text="Percentage of playing handicap applied when handicap_mode='net'.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('wolf_order', models.JSONField(blank=True, default=list, help_text='Ordered player ids; the Wolf rotates through this list one hole at a time.')),
                ('lone_wolf_points', models.PositiveSmallIntegerField(default=3, help_text='Pot for a Lone Wolf hole (Wolf goes alone after watching the drives).')),
                ('blind_wolf_points', models.PositiveSmallIntegerField(default=6, help_text='Pot for a Blind Wolf hole (Wolf declares alone before any tee shots).')),
                ('team_win_points', models.PositiveSmallIntegerField(default=1, help_text='Points each winner nets on a partner (2v2) hole.')),
                ('wolf_loses_ties', models.BooleanField(default=False, help_text='If True a tied hole is awarded to the non-wolf side instead of being a push.')),
                ('non_wolf_bonus', models.BooleanField(default=False, help_text='If True a clean win by the non-wolf side on a partner hole pays double.')),
                ('last_place_wolf_1718', models.BooleanField(default=True, help_text='4-player only: on holes 17 & 18 the player in last place becomes the Wolf (catch-up rule).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foursome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wolf_game', to='tournament.foursome')),
            ],
        ),
        migrations.CreateModel(
            name='WolfHoleDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)])),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('partner', 'Partner'), ('lone', 'Lone Wolf'), ('blind', 'Blind Wolf')], default='pending', max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='games.wolfgame')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wolf_partner_holes', to='core.player')),
            ],
            options={
                'ordering': ['hole_number'],
                'unique_together': {('game', 'hole_number')},
            },
        ),
        migrations.CreateModel(
            name='WolfPlayerHoleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)])),
                ('net_score', models.SmallIntegerField(help_text='The score used for ranking (net/gross/SO-adjusted).')),
                ('role', models.CharField(choices=[('wolf', 'Wolf'), ('partner', 'Partner'), ('opponent', 'Opponent')], default='opponent', max_length=10)),
                ('points', models.DecimalField(decimal_places=2, help_text='Per-hole points; zero-based so each hole sums to 0.', max_digits=5)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_results', to='games.wolfgame')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wolf_hole_results', to='core.player')),
            ],
            options={
                'ordering': ['hole_number', '-points'],
                'unique_together': {('game', 'player', 'hole_number')},
            },
        ),
    ]
