# Generated by Django 6.0.4 on 2026-06-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0030_wolf'),
    ]

    operations = [
        migrations.AddField(
            model_name='wolfgame',
            name='require_lone_or_blind',
            field=models.BooleanField(default=False, help_text='4-player only: every player must go Lone or Blind at least once in holes 1-16.  Once a player has been Wolf 3 times all as partner, their next (last) Wolf turn locks out the partner option.'),
        ),
    ]
