# Generated by Django 6.0.4 on 2026-06-02 05:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_account_fk'),
        ('games', '0031_wolfgame_require_lone_or_blind'),
        ('tournament', '0033_alter_rydercupfoursomeconfig_game_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RabbitGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('halved', 'Halved')], default='pending', max_length=20)),
                ('handicap_mode', models.CharField(choices=[('net', 'Net'), ('gross', 'Gross'), ('strokes_off', 'Strokes Off Low')], default='net', help_text='How per-hole scores are adjusted for ranking.', max_length=20)),
                ('net_percent', models.PositiveSmallIntegerField(default=100, help_text="Percentage of playing handicap applied when handicap_mode='net'.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('accumulate', models.BooleanField(default=True, help_text='True: rabbit builds a lead (+1 win / −1 loss), lost only when the lead hits 0.  False: lost on the first hole the rabbit is beaten.')),
                ('num_segments', models.PositiveSmallIntegerField(default=1, help_text='1 = one 18-hole match, 2 = two 9-hole matches, 3 = three 6-hole matches.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foursome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rabbit_game', to='tournament.foursome')),
            ],
        ),
        migrations.CreateModel(
            name='RabbitHoleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)])),
                ('segment', models.PositiveSmallIntegerField(default=1)),
                ('lead', models.PositiveSmallIntegerField(default=0)),
                ('event', models.CharField(choices=[('grab', 'Grabbed'), ('extend', 'Extended'), ('held', 'Held'), ('beaten', 'Beaten'), ('freed', 'Freed'), ('tie', 'Tie'), ('none', 'None')], default='none', max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_results', to='games.rabbitgame')),
                ('holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rabbit_holes_held', to='core.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rabbit_holes_won', to='core.player')),
            ],
            options={
                'ordering': ['hole_number'],
                'unique_together': {('game', 'hole_number')},
            },
        ),
    ]
