# Generated by Django 6.0.5 on 2026-06-07 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_rabbit'),
        ('tournament', '0035_watcher'),
    ]

    operations = [
        migrations.CreateModel(
            name='StablefordGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handicap_mode', models.CharField(choices=[('net', 'Net'), ('gross', 'Gross'), ('strokes_off', 'Strokes Off Low')], default='net', max_length=20)),
                ('net_percent', models.PositiveSmallIntegerField(default=100)),
                ('pts_albatross', models.SmallIntegerField(default=5)),
                ('pts_eagle', models.SmallIntegerField(default=4)),
                ('pts_birdie', models.SmallIntegerField(default=3)),
                ('pts_par', models.SmallIntegerField(default=2)),
                ('pts_bogey', models.SmallIntegerField(default=1)),
                ('pts_double', models.SmallIntegerField(default=0)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Entry fee per player.', max_digits=8)),
                ('payouts', models.JSONField(default=list, help_text="Payout per finishing place, e.g. [{'place': 1, 'amount': 60}].")),
                ('excluded_player_ids', models.JSONField(default=list)),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stableford_config', to='tournament.round')),
            ],
        ),
    ]
