# Generated by Django 6.0.5 on 2026-06-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0033_stablefordgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='stablefordgame',
            name='payout_style',
            field=models.CharField(choices=[('pool', 'Pool (places paid)'), ('per_point', 'Per point')], default='pool', max_length=12),
        ),
        migrations.AddField(
            model_name='stablefordgame',
            name='per_point_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='$ per point of margin vs each opponent (per_point style).', max_digits=6),
        ),
        migrations.AlterField(
            model_name='stablefordgame',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Entry fee per player (pool style).', max_digits=8),
        ),
    ]
