# Generated by Django 6.0.5 on 2026-06-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0034_stablefordgame_payout_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stablefordgame',
            name='per_point_mode',
            field=models.CharField(choices=[('all', 'Pay everyone above you'), ('first', 'Pay first')], default='all', max_length=8),
        ),
    ]
