# Generated by Django 6.0.5 on 2026-06-07 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0035_stablefordgame_per_point_mode'),
        ('tournament', '0035_watcher'),
    ]

    operations = [
        migrations.CreateModel(
            name='StablefordChampionshipConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handicap_mode', models.CharField(choices=[('net', 'Net'), ('gross', 'Gross'), ('strokes_off', 'Strokes Off Low')], default='net', max_length=20)),
                ('net_percent', models.PositiveSmallIntegerField(default=100)),
                ('pts_albatross', models.SmallIntegerField(default=5)),
                ('pts_eagle', models.SmallIntegerField(default=4)),
                ('pts_birdie', models.SmallIntegerField(default=3)),
                ('pts_par', models.SmallIntegerField(default=2)),
                ('pts_bogey', models.SmallIntegerField(default=1)),
                ('pts_double', models.SmallIntegerField(default=0)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('payouts', models.JSONField(default=list)),
                ('excluded_player_ids', models.JSONField(default=list)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stableford_championship_config', to='tournament.tournament')),
            ],
        ),
    ]
