# Generated by Django 6.0.5 on 2026-06-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0036_stablefordchampionshipconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='nassaugame',
            name='play_back',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nassaugame',
            name='play_front',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nassaugame',
            name='play_overall',
            field=models.BooleanField(default=True),
        ),
    ]
