# Generated by Django 6.0.5 on 2026-06-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0037_nassaugame_play_back_nassaugame_play_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sixessegment',
            name='is_void',
            field=models.BooleanField(default=False, help_text='True if voided due to a mid-round withdrawal; scores 0 points and is excluded from totals.'),
        ),
    ]
