# Generated by Django 6.0.5 on 2026-06-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0038_sixessegment_is_void'),
    ]

    operations = [
        migrations.AddField(
            model_name='points531game',
            name='loss_cap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional per-side loss cap (one table-wide value applied per player). Null = uncapped; the theoretical max 5-3-1 loss is 36 × bet_unit (2 pts/hole below the mean × 18), so a null cap and 36×bet_unit are equivalent. When set lower, losers clip at the cap and winners are reduced pro-rata — see services.wager.settle().', max_digits=8, null=True),
        ),
    ]
