# Generated by Django 6.0.5 on 2026-06-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0039_points531game_loss_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='stablefordgame',
            name='loss_cap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional per-player loss cap (per_point style); null = uncapped.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='stablefordgame',
            name='per_point_mode',
            field=models.CharField(choices=[('average', 'Settle vs the field average'), ('all', 'Pay everyone above you'), ('first', 'Pay first')], default='average', max_length=8),
        ),
    ]
