# Generated by Django 6.0.5 on 2026-06-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0040_stablefordgame_loss_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wolfgame',
            name='loss_cap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional per-player loss cap; null = uncapped.', max_digits=8, null=True),
        ),
    ]
