# Generated by Django 6.0.5 on 2026-06-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0041_wolfgame_loss_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='nassaugame',
            name='loss_cap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Per-side loss cap (presses/Claremont only); null = uncapped.', max_digits=8, null=True),
        ),
    ]
