# Generated by Django 6.0.5 on 2026-06-17 21:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_catalogcourse_course_city_course_country_and_more'),
        ('games', '0042_nassaugame_loss_cap'),
        ('tournament', '0038_alter_rydercupfoursomeconfig_game_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegasGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('halved', 'Halved')], default='pending', max_length=20)),
                ('handicap_mode', models.CharField(choices=[('net', 'Net'), ('gross', 'Gross'), ('strokes_off', 'Strokes Off Low')], default='net', help_text='How net scores (the digits) are derived.', max_length=20)),
                ('net_percent', models.PositiveSmallIntegerField(default=100, help_text="Percent of playing handicap applied when handicap_mode='net'.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('net_max_double_bogey', models.BooleanField(default=True, help_text='Cap each net hole score at net double bogey (par + 2).')),
                ('birdie_mode', models.CharField(choices=[('flip', 'Flip opponents on birdie'), ('multiplier', 'Multiply points on birdie')], default='flip', max_length=12)),
                ('carryover', models.BooleanField(default=False, help_text='Tied holes carry; next win × (carried + 1).')),
                ('loss_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Optional per-side max loss (in points × bet_unit); null = uncapped.', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foursome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vegas_game', to='tournament.foursome')),
            ],
        ),
        migrations.CreateModel(
            name='VegasTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.PositiveSmallIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='games.vegasgame')),
                ('players', models.ManyToManyField(related_name='vegas_teams', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='VegasHoleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.PositiveSmallIntegerField()),
                ('team1_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('team2_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, choices=[('team1', 'Team 1'), ('team2', 'Team 2'), ('halved', 'Halved')], max_length=6, null=True)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('multiplier', models.PositiveSmallIntegerField(default=1)),
                ('carry_count', models.PositiveSmallIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_results', to='games.vegasgame')),
            ],
            options={
                'ordering': ['hole_number'],
                'unique_together': {('game', 'hole_number')},
            },
        ),
    ]
