# Generated by Django 6.0.5 on 2026-06-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0043_vegasgame_vegasteam_vegasholeresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='triplecupgame',
            name='foursomes_first',
            field=models.BooleanField(default=False, help_text='Play the foursomes (alt-shot) segment on holes 1-6 and fourball on 7-12.  Default False = fourball first.  Singles is always 13-18.'),
        ),
    ]
