# Generated by Django 6.0.5 on 2026-06-28 22:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tee_superseded_by'),
        ('games', '0044_triplecupgame_foursomes_first'),
        ('tournament', '0041_alter_rydercupfoursomeconfig_game_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourballGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('halved', 'Halved')], default='pending', max_length=20)),
                ('handicap_mode', models.CharField(choices=[('net', 'Net'), ('gross', 'Gross'), ('strokes_off', 'Strokes Off Low')], default='net', help_text="How each player's per-hole score is derived.", max_length=20)),
                ('net_percent', models.PositiveSmallIntegerField(default=100, help_text='Percent of handicap applied for net / strokes-off modes.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('bet_amount', models.DecimalField(decimal_places=2, default=0, help_text='Match stake per player; winners +, losers −, halve = push.', max_digits=8)),
                ('result', models.CharField(blank=True, choices=[('team1', 'Team 1'), ('team2', 'Team 2'), ('halved', 'Halved')], max_length=6, null=True)),
                ('holes_up_after_final', models.IntegerField(default=0, help_text='Final running margin (positive = Team 1 up).')),
                ('finished_on_hole', models.PositiveSmallIntegerField(blank=True, help_text='Hole the match closed out on (null = went to 18).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foursome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fourball_game', to='tournament.foursome')),
            ],
        ),
        migrations.CreateModel(
            name='FourballHoleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.PositiveSmallIntegerField()),
                ('team1_net', models.IntegerField(blank=True, null=True)),
                ('team2_net', models.IntegerField(blank=True, null=True)),
                ('winning_team_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('holes_up_after', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_results', to='games.fourballgame')),
            ],
            options={
                'ordering': ['hole_number'],
                'unique_together': {('game', 'hole_number')},
            },
        ),
        migrations.CreateModel(
            name='FourballTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.PositiveSmallIntegerField()),
                ('is_winner', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='games.fourballgame')),
                ('players', models.ManyToManyField(related_name='fourball_teams', to='core.player')),
            ],
            options={
                'unique_together': {('game', 'team_number')},
            },
        ),
    ]
