# Generated by Django 6.0.5 on 2026-06-29 22:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_gamesuggestion'),
        ('games', '0045_fourballgame_fourballholeresult_fourballteam'),
        ('tournament', '0042_alter_rydercupfoursomeconfig_game_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotsGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('halved', 'Halved')], default='pending', max_length=20)),
                ('bet_unit', models.DecimalField(decimal_places=2, default=1, help_text='Value of one spot.', max_digits=6)),
                ('payout_style', models.CharField(choices=[('pay_around', 'Pay around'), ('pool', 'Pool')], default='pay_around', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foursome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spots_game', to='tournament.foursome')),
            ],
        ),
        migrations.CreateModel(
            name='SpotsPlayerHoleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)])),
                ('count', models.PositiveSmallIntegerField(default=0, help_text='Number of spots earned by this player on this hole.')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_results', to='games.spotsgame')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots_results', to='core.player')),
            ],
            options={
                'ordering': ['hole_number', 'player_id'],
                'unique_together': {('game', 'player', 'hole_number')},
            },
        ),
    ]
