# Generated by Django 6.0.5 on 2026-06-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0046_spotsgame_spotsplayerholeresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotsplayerholeresult',
            name='count',
            field=models.SmallIntegerField(default=0, help_text='Spots earned by this player on this hole (negative = a reverse spot / penalty).'),
        ),
    ]
