# Generated by Django 6.0.5 on 2026-07-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0047_alter_spotsplayerholeresult_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinsgame',
            name='loss_cap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional per-player loss cap (per_point style); null = uncapped.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='skinsgame',
            name='payout_style',
            field=models.CharField(choices=[('pool', 'Pool'), ('per_point', 'Per skin')], default='pool', max_length=12),
        ),
        migrations.AddField(
            model_name='skinsgame',
            name='per_point_mode',
            field=models.CharField(choices=[('average', 'Settle vs the field average'), ('all', 'Pay everyone above you'), ('first', 'Pay the leader')], default='first', max_length=8),
        ),
        migrations.AddField(
            model_name='skinsgame',
            name='per_point_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='$ per skin of margin (per_point style).', max_digits=6),
        ),
    ]
