# Generated by Django 6.0.5 on 2026-07-05 20:22

from django.db import migrations, models


def _pay_around_to_per_point(apps, schema_editor):
    """Legacy 'pay_around' games → the 2-axis equivalent (per_point + 'all')."""
    SpotsGame = apps.get_model('games', 'SpotsGame')
    SpotsGame.objects.filter(payout_style='pay_around').update(
        payout_style='per_point', per_point_mode='all')


def _per_point_to_pay_around(apps, schema_editor):
    SpotsGame = apps.get_model('games', 'SpotsGame')
    SpotsGame.objects.filter(payout_style='per_point', per_point_mode='all').update(
        payout_style='pay_around')


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0048_skinsgame_loss_cap_skinsgame_payout_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotsgame',
            name='loss_cap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional per-player loss cap (per_point style); null = uncapped.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='spotsgame',
            name='per_point_mode',
            field=models.CharField(choices=[('average', 'Settle vs the field average'), ('all', 'Pay everyone above you'), ('first', 'Pay the leader')], default='all', max_length=8),
        ),
        migrations.AlterField(
            model_name='spotsgame',
            name='payout_style',
            field=models.CharField(choices=[('pool', 'Pool'), ('per_point', 'Per spot')], default='per_point', max_length=12),
        ),
        migrations.RunPython(_pay_around_to_per_point, _per_point_to_pay_around),
    ]
