# Generated by Django 6.0.5 on 2026-07-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0049_spotsgame_loss_cap_spotsgame_per_point_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='points531game',
            name='payout_style',
            field=models.CharField(choices=[('pool', 'Pool'), ('per_point', 'Per point')], default='per_point', max_length=12),
        ),
        migrations.AddField(
            model_name='points531game',
            name='per_point_mode',
            field=models.CharField(choices=[('average', 'Settle vs the field average'), ('all', 'Pay everyone above you'), ('first', 'Pay the leader')], default='average', max_length=8),
        ),
    ]
