# Generated by Django 6.0.5 on 2026-07-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0050_points531game_payout_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nassaugame',
            name='single_match',
            field=models.BooleanField(default=False),
        ),
    ]
