# Generated by Django 6.0.5 on 2026-07-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0051_nassaugame_single_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='lownetroundconfig',
            name='participant_player_ids',
            field=models.JSONField(default=list, help_text='Player IDs actually IN this game (a SUBSET side game — e.g. 2 of a 4-some). Empty = all real players in the round. excluded_player_ids must be a subset of these. See docs/parallel-games.md.'),
        ),
        migrations.AddField(
            model_name='stablefordgame',
            name='participant_player_ids',
            field=models.JSONField(default=list),
        ),
    ]
