# Generated by Django 6.0.5 on 2026-07-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0052_lownetroundconfig_participant_player_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinsgame',
            name='participant_player_ids',
            field=models.JSONField(default=list),
        ),
    ]
