# Generated by Django 6.0.5 on 2026-07-13 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0053_skinsgame_participant_player_ids'),
        ('tournament', '0047_alter_rydercupfoursomeconfig_game_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nassaugame',
            name='game_type',
            field=models.CharField(choices=[('nassau', 'Nassau'), ('nassau_nine', 'Nassau Nine'), ('match_18', 'Singles Match')], default='nassau', help_text='Which Nassau-family match this row is; matches the Round.active_games slug.', max_length=20),
        ),
        migrations.AlterField(
            model_name='nassaugame',
            name='foursome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nassau_games', to='tournament.foursome'),
        ),
        migrations.AlterUniqueTogether(
            name='nassaugame',
            unique_together={('foursome', 'game_type')},
        ),
    ]
