# Generated by Django 6.0.5 on 2026-07-13 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_player_ghin'),
        ('games', '0054_nassaugame_game_type_alter_nassaugame_foursome_and_more'),
        ('tournament', '0047_alter_rydercupfoursomeconfig_game_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiSkinsLinkedRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_rounds', to='games.multiskinsgame')),
                ('linked_by', models.ForeignKey(blank=True, help_text='Player who linked this round to the pool.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.player')),
                ('round', models.ForeignKey(help_text='A round whose scores feed this pool.', on_delete=django.db.models.deletion.CASCADE, related_name='linked_skins_pools', to='tournament.round')),
            ],
            options={
                'unique_together': {('game', 'round')},
            },
        ),
    ]
