# Generated by Django 6.0.4 on 2026-07-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0057_honorsgame_participant_player_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbitgame',
            name='handicap_allocation',
            field=models.CharField(choices=[('per_segment', 'Spread across the matches'), ('full_round', 'Straight up (round-wide SI)')], default='per_segment', help_text="Strokes-Off only: 'per_segment' splits each golfer's strokes evenly across the matches, allocated to the hardest holes in each range; 'full_round' allocates round-wide by stroke index.  No effect for net/gross or 1 segment.", max_length=20),
        ),
    ]
