# Generated by Django 6.0.4 on 2026-07-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0058_rabbitgame_handicap_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbitgame',
            name='extra_rabbits',
            field=models.BooleanField(default=False, help_text="ACCUMULATE ONLY.  When a leg is decided early (the holder's lead exceeds the holes left), the next leg starts on the very next hole and any leftover holes start a fresh 'extra' rabbit (loose) — up to two.  A rabbit that runs a single hole is worth half the stake.  No effect in stop-after-one mode."),
        ),
    ]
