# Generated by Django 6.0.4 on 2026-08-01 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0059_rabbitgame_extra_rabbits'),
        ('tournament', '0049_alter_rydercupfoursomeconfig_game_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nassaugame',
            name='game_type',
            field=models.CharField(choices=[('nassau', 'Nassau'), ('nassau_nine', 'Nassau Nine'), ('match_18', 'Singles Match'), ('triple_1', 'Triple Nassau — match 1'), ('triple_2', 'Triple Nassau — match 2'), ('triple_3', 'Triple Nassau — match 3')], default='nassau', help_text='Which Nassau-family match this row is; matches the Round.active_games slug.', max_length=20),
        ),
        migrations.CreateModel(
            name='TripleNassauGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_order', models.JSONField(default=list, help_text='Player PKs in display order (3 entries).')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('halved', 'Halved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foursome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triple_nassau_games', to='tournament.foursome')),
            ],
        ),
        migrations.AddField(
            model_name='nassaugame',
            name='triple_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='games.triplenassaugame'),
        ),
    ]
