# Generated by Django 6.0.4 on 2026-08-11 22:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backfill_tee_curation_and_sync_version'),
        ('games', '0060_alter_nassaugame_game_type_triplenassaugame_and_more'),
        ('tournament', '0050_alter_rydercupfoursomeconfig_game_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamHoleScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)])),
                ('gross_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('handicap_strokes', models.PositiveSmallIntegerField(default=0)),
                ('net_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('chosen_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.player')),
                ('foursome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_hole_scores', to='tournament.foursome')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournament.tournamentteam')),
            ],
            options={
                'ordering': ['hole_number'],
                'unique_together': {('foursome', 'team', 'hole_number')},
            },
        ),
    ]
