# Generated by Django 6.0.4 on 2026-08-15 15:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backfill_tee_curation_and_sync_version'),
        ('games', '0061_teamholescore'),
        ('tournament', '0051_alter_rydercupfoursomeconfig_game_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurvivorGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('halved', 'Halved')], default='pending', max_length=20)),
                ('handicap_mode', models.CharField(choices=[('net', 'Net'), ('gross', 'Gross'), ('strokes_off', 'Strokes Off Low')], default='net', help_text='How per-hole scores are adjusted for ranking.', max_length=20)),
                ('net_percent', models.PositiveSmallIntegerField(default=100, help_text="Percentage of playing handicap applied when handicap_mode='net' or 'strokes_off'.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('foursome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survivor_game', to='tournament.foursome')),
            ],
        ),
        migrations.CreateModel(
            name='SurvivorHoleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)])),
                ('survivor_index', models.PositiveSmallIntegerField(default=1)),
                ('role', models.CharField(choices=[('elimination', 'Elimination'), ('decider', 'Decider'), ('final', 'Final hole')], default='elimination', max_length=12)),
                ('event', models.CharField(choices=[('eliminated', 'Eliminated'), ('no_elimination', 'No elimination'), ('won', 'Won'), ('carried', 'Carried'), ('split', 'Split'), ('no_blood', 'No blood')], default='no_elimination', max_length=16)),
                ('eliminated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survivor_holes_eliminated', to='core.player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_results', to='games.survivorgame')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survivor_holes_won', to='core.player')),
            ],
            options={
                'ordering': ['hole_number'],
                'unique_together': {('game', 'hole_number')},
            },
        ),
    ]
