# Generated by Django 6.0.4 on 2026-08-16 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backfill_tee_curation_and_sync_version'),
        ('games', '0062_survivorgame_survivorholeresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivorgame',
            name='zombie_option',
            field=models.BooleanField(default=False, help_text='When on, the eliminated player (the Zombie) keeps playing; going strictly low on a decider hole brings them back in and sends a decider out instead, so a Survivor can run long.'),
        ),
        migrations.AddField(
            model_name='survivorholeresult',
            name='resurrected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survivor_holes_resurrected', to='core.player'),
        ),
        migrations.AlterField(
            model_name='survivorholeresult',
            name='event',
            field=models.CharField(choices=[('eliminated', 'Eliminated'), ('no_elimination', 'No elimination'), ('won', 'Won'), ('carried', 'Carried'), ('split', 'Split'), ('no_blood', 'No blood'), ('resurrected', 'Resurrected'), ('killed', 'Killed by the Zombie')], default='no_elimination', max_length=16),
        ),
    ]
