# Generated by Django 6.0.4 on 2026-08-17 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backfill_tee_curation_and_sync_version'),
        ('games', '0063_survivorgame_zombie_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplaymatch',
            name='trophy_player',
            field=models.ForeignKey(blank=True, help_text='Halved match only: who takes the trophy and the next-stage seat, by last hole won.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mp_trophies_on_last_hole', to='core.player'),
        ),
    ]
