# Generated by Django 6.0.4 on 2026-08-17 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0064_matchplaymatch_trophy_player'),
        ('tournament', '0053_foursome_is_champions_foursome'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniSinglesConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handicap_mode', models.CharField(choices=[('net', 'Net'), ('gross', 'Gross'), ('strokes_off', 'Strokes Off Low')], default='strokes_off', max_length=20)),
                ('net_percent', models.PositiveSmallIntegerField(default=100)),
                ('day1_entry_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Per golfer. Everybody in the field is in a day-1 bracket; the pot is paid inside each group.', max_digits=8)),
                ('day1_payouts', models.JSONField(default=list, help_text="[{'place': 1, 'amount': 24.00}, …] per group.")),
                ('day2_payouts', models.JSONField(default=list, help_text='Day-2 places, paid out of the championship carve-out. 4th takes nothing — there is no day-2 entry to refund.')),
                ('empty_seat_rule', models.CharField(choices=[('promote', 'Promote the best runner-up'), ('points', 'Points, then a match'), ('short', 'Play it short-handed')], default='promote', help_text='Three groups, or a winner who withdraws — one rule, set once, never asked on Sunday.', max_length=10)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mini_singles_config', to='tournament.tournament')),
            ],
        ),
    ]
