# Generated by Django 6.0.4 on 2026-08-17 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0065_minisinglesconfig'),
        ('tournament', '0053_foursome_is_champions_foursome'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayBetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Per eligible golfer. The ineligible do not pay in, so the pool is provisional until the championship closes.', max_digits=8)),
                ('payouts', models.JSONField(default=list, help_text="[{'place': 1, 'amount': 100.00}, …]. Trimmed to the number of places the eligible field supports.")),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='day_bet_config', to='tournament.round')),
            ],
        ),
    ]
