"""
The ball game stops asking the colour and starts asking the NAME.

Hand-edited from the autogenerated remove+add, which would have thrown the
existing colours away. This renames the column and carries each value across:
a round configured as "Red" becomes "Red Ball", so an in-flight tournament
keeps a tab that reads like a game rather than a paint chip. Anything already
containing "ball" is left alone, and anything over the 16-character cap is
trimmed to it.
"""
from django.db import migrations, models


def _colour_to_name(apps, schema_editor):
    PinkBallConfig = apps.get_model('games', 'PinkBallConfig')
    for cfg in PinkBallConfig.objects.all():
        value = (cfg.game_name or '').strip()
        if not value:
            continue
        if 'ball' not in value.lower():
            value = f'{value} Ball'
        cfg.game_name = value[:16]
        cfg.save(update_fields=['game_name'])


def _noop(apps, schema_editor):
    """Reversing just leaves the names in place — they are still valid text."""


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0066_daybetconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pinkballconfig',
            options={'verbose_name': 'Ball Game Config'},
        ),
        migrations.RenameField(
            model_name='pinkballconfig',
            old_name='ball_color',
            new_name='game_name',
        ),
        migrations.AlterField(
            model_name='pinkballconfig',
            name='game_name',
            field=models.CharField(
                blank=True, default='', max_length=16,
                help_text='What this group calls the game — "Pink Ball", '
                          '"Devil Ball", "Beer Ball". 16 characters. No '
                          'default; required to save.'),
        ),
        migrations.RunPython(_colour_to_name, _noop),
        migrations.AlterField(
            model_name='pinkballconfig',
            name='entry_fee',
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=8,
                help_text='Entry fee per golfer; total pool = entry_fee × field size.'),
        ),
    ]
