# Generated by Django 6.0.4 on 2026-08-22 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0067_ball_game_name'),
        ('tournament', '0053_foursome_is_champions_foursome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamholescore',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournament.tournamentteam'),
        ),
    ]
