# Generated by Django 6.0.4 on 2026-08-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0068_alter_teamholescore_team'),
        ('tournament', '0056_alter_teamplayteamstate_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamholescore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teamholescore',
            name='team_play_slot',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='teamholescore',
            unique_together={('foursome', 'team', 'team_play_slot', 'hole_number')},
        ),
    ]
