# Generated by Django 6.0.4 on 2026-08-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0069_alter_teamholescore_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivorgame',
            name='zombie_option',
            field=models.BooleanField(default=True, help_text='When on, the eliminated player (the Zombie) keeps playing; going strictly low on a decider hole brings them back in and sends a decider out instead, so a Survivor can run long.'),
        ),
    ]
