# Generated by Django 6.0.4 on 2026-09-05 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tee_custom_index_of'),
        ('games', '0070_alter_survivorgame_zombie_option'),
        ('tournament', '0066_alter_rydercupfoursomeconfig_game_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequoyaThreesGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='in_progress', max_length=20)),
                ('handicap_mode', models.CharField(choices=[('net', 'Net'), ('gross', 'Gross'), ('strokes_off', 'Strokes Off Low')], default='net', max_length=20)),
                ('net_percent', models.PositiveSmallIntegerField(default=100)),
                ('bet_amount', models.DecimalField(decimal_places=2, default=5, max_digits=8)),
                ('press_mode', models.CharField(choices=[('none', 'No presses'), ('auto', 'Auto after the first hole won'), ('manual_auto', 'Auto, plus one press called by hand')], default='auto', max_length=20)),
                ('match1_side1', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foursome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sequoya_threes_game', to='tournament.foursome')),
            ],
        ),
        migrations.CreateModel(
            name='SequoyaThreesPress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_index', models.PositiveSmallIntegerField(help_text='1-6.')),
                ('side', models.PositiveSmallIntegerField()),
                ('start_hole', models.PositiveSmallIntegerField(help_text='First hole the press covers — after the call.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequoya_threes_presses', to='core.player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presses', to='games.sequoyathreesgame')),
            ],
            options={
                'ordering': ['match_index', 'start_hole'],
                'constraints': [models.UniqueConstraint(fields=('game', 'match_index'), name='sequoya_one_manual_press_per_match')],
            },
        ),
    ]
