# Generated by Django 6.0.4 on 2026-09-05 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_favoritegolfer'),
        ('games', '0072_alter_sequoyathreesgame_handicap_mode'),
        ('tournament', '0068_alter_rydercupfoursomeconfig_game_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='in_progress', max_length=20)),
                ('handicap_mode', models.CharField(choices=[('net', 'Net'), ('gross', 'Gross'), ('strokes_off', 'Strokes Off Low')], default='net', max_length=20)),
                ('net_percent', models.PositiveSmallIntegerField(default=100)),
                ('min_bet', models.DecimalField(decimal_places=2, default=5, max_digits=8)),
                ('max_bet', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('rotation_rule', models.CharField(choices=[('ask', 'The group says who holed out first'), ('draw', 'Tied low scores are drawn'), ('keep', 'The current banker keeps it')], default='ask', max_length=10)),
                ('hole_cap_enabled', models.BooleanField(default=False)),
                ('hole_cap_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_banker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banker_games_opened', to='core.player')),
                ('foursome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banker_game', to='tournament.foursome')),
            ],
        ),
        migrations.CreateModel(
            name='BankerHole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.PositiveSmallIntegerField()),
                ('max_bet', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('countered', models.BooleanField(default=False)),
                ('tie_reason', models.CharField(blank=True, choices=[('holed_first', 'The group said who holed out first'), ('drawn', 'Drawn at random'), ('kept', 'The banker kept it')], max_length=20)),
                ('banker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banker_holes_banked', to='core.player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holes', to='games.bankergame')),
            ],
            options={
                'ordering': ['hole_number'],
            },
        ),
        migrations.CreateModel(
            name='BankerBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('own_multiplier', models.PositiveSmallIntegerField(default=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banker_bets', to='core.player')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='games.bankerhole')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='bankerhole',
            constraint=models.UniqueConstraint(fields=('game', 'hole_number'), name='banker_one_row_per_hole'),
        ),
        migrations.AddConstraint(
            model_name='bankerbet',
            constraint=models.UniqueConstraint(fields=('hole', 'player'), name='banker_one_bet_per_opponent'),
        ),
    ]
