# Generated by Django 6.0.4 on 2026-09-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0073_bankergame_bankerhole_bankerbet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankergame',
            name='handicap_mode',
            field=models.CharField(choices=[('net', 'Net'), ('gross', 'Gross'), ('strokes_off', 'Strokes Off Low')], default='strokes_off', max_length=20),
        ),
    ]
