# Generated by Django 6.0.4 on 2026-09-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0074_alter_bankergame_handicap_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankergame',
            name='allow_counter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bankergame',
            name='allow_player_double',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bankergame',
            name='birdie_bonus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bankergame',
            name='par3_triples',
            field=models.BooleanField(default=True),
        ),
    ]
