# Generated by Django 6.0.4 on 2026-09-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0075_bankergame_allow_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankergame',
            name='loss_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
