# Generated by Django 6.0.4 on 2026-09-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0076_bankergame_loss_cap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankergame',
            name='loss_cap',
        ),
        migrations.AddField(
            model_name='bankergame',
            name='loss_caps',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
