# Generated by Django 6.0.4 on 2026-09-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0077_remove_bankergame_loss_cap_bankergame_loss_caps'),
    ]

    operations = [
        migrations.AddField(
            model_name='lownetchampionshipconfig',
            name='excluded_player_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
