# Generated by Django 6.0.4 on 2026-09-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0078_lownetchampionshipconfig_excluded_player_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegasholeresult',
            name='team1_capped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vegasholeresult',
            name='team1_flipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vegasholeresult',
            name='team2_capped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vegasholeresult',
            name='team2_flipped',
            field=models.BooleanField(default=False),
        ),
    ]
