# Generated by Django 6.0.4 on 2026-09-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0079_vegasholeresult_team1_capped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sixessegment',
            name='handicap_allocation',
            field=models.CharField(choices=[('per_segment', 'Spread across 3 segments'), ('full_round', 'Round-wide (strokes on hardest holes)')], default='full_round', help_text="Only meaningful for handicap_mode='strokes_off'. 'full_round' (the default) allocates strokes by round-wide stroke index — 'Straight up' on the setup screen; 'per_segment' splits SO across the 3 matches, which was the original Sixes rule and the default until 17 Sep 2026.", max_length=20),
        ),
    ]
