# Generated by Django 6.0.4 on 2026-09-22 20:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0080_alter_sixessegment_handicap_allocation'),
        ('tournament', '0072_alter_rydercupfoursomeconfig_game_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetterBallConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balls_to_count', models.PositiveSmallIntegerField(default=2, help_text='Nets counted per group per hole, 1-4. Fixed for all eighteen holes — a count that moves is Irish Rumble.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('name', models.CharField(blank=True, default='', help_text='TD-chosen name. Blank = derived from the ball count (see services.better_ball).', max_length=40)),
                ('handicap_mode', models.CharField(choices=[('net', 'Net'), ('gross', 'Gross'), ('strokes_off', 'Strokes Off Low')], default='net', max_length=20)),
                ('net_percent', models.PositiveSmallIntegerField(default=85, help_text='Percentage of playing handicap in net mode.')),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Entry per GOLFER; pool = fee × field size.', max_digits=8)),
                ('payouts', models.JSONField(default=list, help_text="Payout per finishing place, e.g. [{'place': 1, 'amount': 70.00}]")),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='better_ball_config', to='tournament.round')),
            ],
        ),
    ]
