# Generated by Django 6.0.4 on 2026-09-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0081_betterballconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbitgame',
            name='handicap_allocation',
            field=models.CharField(choices=[('per_segment', 'Spread across the matches'), ('full_round', 'Straight up (round-wide SI)')], default='full_round', help_text="Strokes-Off only: 'full_round' (the default) allocates strokes round-wide by stroke index — 'Straight up' on the setup screen; 'per_segment' splits each golfer's strokes evenly across the matches, allocated to the hardest holes in each range.  No effect for net/gross or 1 segment.  Defaulted per_segment until 22 Sep 2026, when it followed Sixes.", max_length=20),
        ),
    ]
