# Generated by Django 6.0.4 on 2026-09-26 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0082_alter_rabbitgame_handicap_allocation'),
        ('tournament', '0073_alter_rydercupfoursomeconfig_game_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EclecticConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_on', models.BooleanField(default=True)),
                ('net_on', models.BooleanField(default=True)),
                ('gross_entry_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Per-golfer entry for the GROSS pool.', max_digits=8)),
                ('gross_payouts', models.JSONField(default=list, help_text="[{'place': 1, 'amount': 160.00}, …]")),
                ('net_entry_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Per-golfer entry for the NET pool.', max_digits=8)),
                ('net_payouts', models.JSONField(default=list, help_text="[{'place': 1, 'amount': 160.00}, …]")),
                ('excluded_player_ids', models.JSONField(blank=True, default=list)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eclectic_config', to='tournament.tournament')),
            ],
            options={
                'verbose_name': 'Eclectic Config',
            },
        ),
    ]
