# Generated by Django 6.0.4 on 2026-09-26 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0083_eclecticconfig'),
        ('tournament', '0074_alter_rydercupfoursomeconfig_game_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortyBallsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handicap_mode', models.CharField(choices=[('net', 'Net'), ('gross', 'Gross'), ('strokes_off', 'Strokes Off Low')], default='net', max_length=20)),
                ('net_percent', models.PositiveSmallIntegerField(default=100)),
                ('net_max_double_bogey', models.BooleanField(default=True)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Per-golfer entry; the pool is a group prize.', max_digits=8)),
                ('payouts', models.JSONField(default=list, help_text="[{'place': 1, 'amount': 150.00}, …]")),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forty_balls_config', to='tournament.round')),
            ],
            options={
                'verbose_name': '40 Balls Config',
            },
        ),
        migrations.CreateModel(
            name='FortyBallsHoleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.PositiveSmallIntegerField()),
                ('count', models.PositiveSmallIntegerField()),
                ('app_set', models.BooleanField(default=False)),
                ('foursome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forty_balls_counts', to='tournament.foursome')),
            ],
            options={
                'verbose_name': '40 Balls Hole Count',
                'ordering': ['hole_number'],
                'constraints': [models.UniqueConstraint(fields=('foursome', 'hole_number'), name='forty_balls_one_count_per_hole')],
            },
        ),
    ]
