# Generated by Django 6.0.4 on 2026-09-28 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_favoritegolfer'),
        ('games', '0084_fortyballsconfig_fortyballsholecount'),
        ('tournament', '0074_alter_rydercupfoursomeconfig_game_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadTripConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_on', models.BooleanField(default=True)),
                ('gross_on', models.BooleanField(default=True)),
                ('handicap_mode', models.CharField(choices=[('locked', 'Locked for the trip'), ('updated', 'Updated before each round')], default='updated', max_length=10)),
                ('net_max_double_bogey', models.BooleanField(default=True)),
                ('gross_max_double_bogey', models.BooleanField(default=False)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='road_trip_config', to='tournament.tournament')),
            ],
            options={
                'verbose_name': 'Road Trip Config',
            },
        ),
        migrations.CreateModel(
            name='RoadTripIndexAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_round_number', models.PositiveSmallIntegerField()),
                ('handicap_index', models.DecimalField(decimal_places=1, max_digits=4)),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='road_trip_adjustments', to='core.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='road_trip_index_adjustments', to='tournament.tournament')),
            ],
            options={
                'verbose_name': 'Road Trip Index Adjustment',
                'ordering': ['from_round_number', 'created_at'],
                'indexes': [models.Index(fields=['tournament', 'player'], name='games_roadt_tournam_98b5a7_idx')],
            },
        ),
    ]
