# Generated by Django 6.0.4 on 2026-09-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0085_roadtripconfig_roadtripindexadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadtripconfig',
            name='starting_indexes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
