# Generated by Django 6.0.4 on 2026-09-29 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0087_rename_eclecticconfig_dreamroundconfig'),
        ('tournament', '0075_alter_rydercupfoursomeconfig_game_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dreamroundconfig',
            options={'verbose_name': 'Dream Round Config'},
        ),
        migrations.AlterField(
            model_name='dreamroundconfig',
            name='tournament',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dream_round_config', to='tournament.tournament'),
        ),
    ]
