# Generated by Django 6.0.4 on 2026-09-30 17:18

import django.core.validators
"""Triple Cup: one handicap allowance per segment.

The new fields carry WHS defaults (90% four-ball, 100% singles) for games
made from here on. **Existing games must not move**, so the data migration
writes the old single `net_percent` onto both segments and folds it into the
alt-shot weights — where it used to be applied as a second multiplier.

    old alt-shot combined = (L·low + H·high)/100 · net/100
    new alt-shot combined = (L·low' + H·high')/100 ,  pct' = pct · net/100

which is the same number. A round part-way through keeps the strokes it has
been scoring with; without this, applying the migration mid-round would
re-net every hole already played.
"""
from django.db import migrations, models


def carry_the_old_allowance(apps, schema_editor):
    Game = apps.get_model('games', 'TripleCupGame')
    for g in Game.objects.all():
        net = g.net_percent if g.net_percent is not None else 100
        g.fourball_percent = net
        g.singles_percent = net
        if net != 100:
            # Integer percents, so this is exact for the values the UI can
            # produce (50 x 90% = 45); round rather than truncate for any
            # hand-set odd one.
            g.alt_shot_low_pct = int(round(g.alt_shot_low_pct * net / 100.0))
            g.alt_shot_high_pct = int(round(g.alt_shot_high_pct * net / 100.0))
        g.save(update_fields=['fourball_percent', 'singles_percent',
                              'alt_shot_low_pct', 'alt_shot_high_pct'])


def back_to_one_allowance(apps, schema_editor):
    """Reverse: four-ball's allowance was the single one, and the alt-shot
    weights go back to carrying it as a multiplier."""
    Game = apps.get_model('games', 'TripleCupGame')
    for g in Game.objects.all():
        net = g.fourball_percent if g.fourball_percent is not None else 100
        g.net_percent = net
        if net:
            g.alt_shot_low_pct = int(round(g.alt_shot_low_pct * 100.0 / net))
            g.alt_shot_high_pct = int(round(g.alt_shot_high_pct * 100.0 / net))
        g.save(update_fields=['net_percent', 'alt_shot_low_pct',
                              'alt_shot_high_pct'])



class Migration(migrations.Migration):

    dependencies = [
        ('games', '0088_alter_dreamroundconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triplecupgame',
            name='fourball_percent',
            field=models.PositiveSmallIntegerField(default=90, help_text='% of playing handicap in the four-ball segment. WHS four-ball match play is 90%.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='triplecupgame',
            name='singles_percent',
            field=models.PositiveSmallIntegerField(default=100, help_text='% of playing handicap in the singles segment. WHS singles match play is 100%.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.RunPython(carry_the_old_allowance, back_to_one_allowance),
    ]
