# Generated by Django 6.0.4 on 2026-10-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0089_triple_cup_segment_allowances'),
    ]

    operations = [
        migrations.AddField(
            model_name='triplecupgame',
            name='alt_shot_half_strokes',
            field=models.BooleanField(default=False, help_text='Round the alt-shot differential to the nearest half stroke; the half is played on the hardest hole in the segment and wins that hole if the nets are level.'),
        ),
    ]
