# Generated by Django 6.0.4 on 2026-10-09 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0090_alt_shot_half_strokes'),
        ('tournament', '0078_foursome_hot_spot_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotSpotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoring', models.CharField(choices=[('to_par', 'Strokes to par'), ('stableford', 'Stableford')], default='to_par', max_length=12)),
                ('handicap_mode', models.CharField(choices=[('net', 'Net'), ('gross', 'Gross'), ('strokes_off', 'Strokes Off Low')], default='net', help_text='Net or gross only — there is no low golfer to play strokes off against a whole field.', max_length=20)),
                ('net_percent', models.PositiveSmallIntegerField(default=85, help_text='Allowance applied to the playing handicap. 85% by default, as the handoff specifies; the setup slider runs 50-130.')),
                ('finish_rule', models.CharField(choices=[('keep_rotating', 'Keep rotating'), ('best_2', 'Best 2'), ('three_then_four', '3 then 4')], default='keep_rotating', max_length=20)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Entry fee per foursome; pool = fee x groups.', max_digits=8)),
                ('payouts', models.JSONField(default=list, help_text="Payout per finishing place, as Irish Rumble: [{'place': 1, 'amount': 50.00}, ...]")),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hot_spot_config', to='tournament.round')),
            ],
        ),
        migrations.CreateModel(
            name='HotSpotResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, help_text='Net-to-par under to_par scoring, or total points under stableford.  Null until every hole is in.', null=True)),
                ('holes_in', models.PositiveSmallIntegerField(default=0, help_text='Holes fully scored, for the live board.')),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('foursome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_spot_results', to='tournament.foursome')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_spot_results', to='tournament.round')),
            ],
            options={
                'ordering': ('rank', 'foursome__group_number'),
                'unique_together': {('round', 'foursome')},
            },
        ),
    ]
