#!/usr/bin/env python3
"""SEO build step and audit for halved.golf.

Run it after build-guides.py (or after hand-editing any page) and before
build-zip.sh — build-zip.sh now runs it for you and refuses to zip on errors.

    ./build-seo.py            # update pages + sitemap, then audit
    ./build-seo.py --check    # write nothing; fail if anything is stale or wrong (CI)

What it does, per page:

  * Adds a generated block to <head>, between the `seo:begin` / `seo:end`
    comments. Everything in it is derived from the page itself, so the block is
    rebuilt from scratch on every run and hand-edits inside it are overwritten.
    The page's own tags always win: the block only fills in what the page
    doesn't already declare (canonical, description, Open Graph, Twitter), plus:
      - the iOS Smart App Banner (`apple-itunes-app`)
      - JSON-LD: Organization + WebSite + MobileApplication on the homepage,
        CollectionPage + ItemList on /games/, Article + BreadcrumbList on every
        guide. FAQPage schema stays with build-guides.py, which owns it.
  * Regenerates sitemap.xml from the pages on disk. A page's <lastmod> moves
    only when its content changes (tracked by hash in seo-manifest.json), so
    re-running this script — or regenerating the SEO block — never makes every
    page look freshly edited.

Then it audits the finished site and exits non-zero on errors: missing or
duplicate titles, missing descriptions, canonicals that don't match the URL the
page is served at, anything other than one <h1>, images without alt, invalid
JSON-LD, and internal links that 404. Warnings cover things that work but cost
something: long titles, links that take a redirect, pages nothing links to.

URLs follow how Cloudflare Pages serves the zip: `games/nassau/index.html` is
`/games/nassau/`, and `privacy.html` is `/privacy` (Pages 308s the .html form).

Standard library only, like build-guides.py.
"""
import datetime
import hashlib
import html
import json
import os
import re
import subprocess
import sys
from html.parser import HTMLParser
from urllib.parse import urljoin, urlsplit

ROOT = os.path.dirname(os.path.abspath(__file__))

# --- Site facts -------------------------------------------------------------
SITE = 'https://halved.golf'
BRAND = 'Halved'
APP_NAME = 'Halved Golf'            # the App Store listing name
APP_STORE_ID = '6768284628'
APP_STORE_URL = 'https://apps.apple.com/app/id' + APP_STORE_ID
# Set to 'golf.halved.app' once Android leaves closed testing: adds Android to
# the app schema and the Play listing to the Organization's sameAs.
PLAY_PACKAGE = None
CONTACT_EMAIL = 'info@halved.golf'
OG_IMAGE = SITE + '/og.png'
OG_IMAGE_ALT = 'Halved — every game on your round, scored live and settled to the dollar.'

# Descriptions for pages that don't carry their own. A page's own
# <meta name="description"> always wins over these.
DESCRIPTIONS = {
    'support.html': 'Get help with Halved, the golf scoring app for your group: '
                    'how to reach us, delete your account, and answers to common questions.',
    'privacy.html': 'What information the Halved golf scoring app collects, how it is used, '
                    'and the choices you have — including deleting your account.',
    'delete-account.html': 'How to delete your Halved account and personal data, '
                           'in the app or by email, with or without the app installed.',
    'sms-consent.html': 'How Halved users consent to SMS: one text type only, a one-time '
                        'sign-in passcode. No marketing messages, ever.',
}

# Pages to keep out of search and out of the sitemap, by file path.
NOINDEX = set()

# Files that are not pages on the site.
SKIP_DIRS = {'.git', 'node_modules'}

MANIFEST = os.path.join(ROOT, 'seo-manifest.json')
SITEMAP = os.path.join(ROOT, 'sitemap.xml')

BEGIN = '<!-- seo:begin — generated by build-seo.py; edit the script, not this block -->'
END = '<!-- seo:end -->'
BLOCK_RE = re.compile(r'\n?<!-- seo:begin.*?<!-- seo:end -->', re.S)

TITLE_WARN = 65      # Google trims around 600px, roughly 60–65 characters
DESC_MIN, DESC_MAX = 50, 165

ORG_ID = SITE + '/#organization'
WEBSITE_ID = SITE + '/#website'
APP_ID = SITE + '/#app'


# --- Reading pages ----------------------------------------------------------

class PageParser(HTMLParser):
    """Collects the handful of things SEO cares about from one page."""

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.title = None
        self.meta = {}           # name/property -> [content, ...]
        self.links = {}          # rel -> [href, ...]
        self.h1 = []
        self.imgs = []           # (src, has_alt)
        self.hrefs = []
        self.ld = []             # raw JSON-LD strings
        self.noindex = False
        self._in_title = False
        self._title_buf = []
        self._h1_depth = 0
        self._h1_buf = []
        self._ld_buf = None

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        if tag == 'title':
            self._in_title = True
        elif tag == 'meta':
            key = a.get('name') or a.get('property')
            if key:
                self.meta.setdefault(key.lower(), []).append(a.get('content') or '')
                if key.lower() == 'robots' and 'noindex' in (a.get('content') or '').lower():
                    self.noindex = True
        elif tag == 'link':
            for rel in (a.get('rel') or '').lower().split():
                self.links.setdefault(rel, []).append(a.get('href') or '')
        elif tag == 'h1':
            self._h1_depth += 1
            self._h1_buf = []
        elif tag == 'img':
            self.imgs.append((a.get('src') or '', 'alt' in a))
        elif tag == 'a' and a.get('href') is not None:
            self.hrefs.append(a['href'])
        elif tag == 'script' and (a.get('type') or '').lower() == 'application/ld+json':
            self._ld_buf = []

    def handle_endtag(self, tag):
        if tag == 'title' and self._in_title:
            self._in_title = False
            self.title = ''.join(self._title_buf).strip()
        elif tag == 'h1' and self._h1_depth:
            self._h1_depth -= 1
            self.h1.append(re.sub(r'\s+', ' ', ''.join(self._h1_buf)).strip())
        elif tag == 'script' and self._ld_buf is not None:
            self.ld.append(''.join(self._ld_buf))
            self._ld_buf = None

    def handle_data(self, data):
        if self._in_title:
            self._title_buf.append(data)
        if self._h1_depth:
            self._h1_buf.append(data)
        if self._ld_buf is not None:
            self._ld_buf.append(data)

    def first(self, key):
        v = self.meta.get(key)
        return v[0] if v else None


def parse(text):
    p = PageParser()
    p.feed(text)
    p.close()
    return p


def find_pages():
    """Every .html file under the site root, as paths relative to it."""
    out = []
    for d, dirs, files in os.walk(ROOT):
        dirs[:] = sorted(x for x in dirs if x not in SKIP_DIRS)
        for f in sorted(files):
            if f.endswith('.html'):
                out.append(os.path.relpath(os.path.join(d, f), ROOT).replace(os.sep, '/'))
    return out


def url_path(rel):
    """How Cloudflare Pages serves a file: index.html -> its folder with a
    trailing slash, anything else .html -> the extensionless path."""
    if rel == 'index.html':
        return '/'
    if rel.endswith('/index.html'):
        return '/' + rel[:-len('index.html')]
    return '/' + rel[:-len('.html')]


def kind_of(path):
    if path == '/':
        return 'home'
    if path == '/games/':
        return 'hub'
    if path.startswith('/games/'):
        return 'guide'
    return 'page'


def strip_block(text):
    return BLOCK_RE.sub('', text)


def game_name(h1, path):
    """'How to play a Nassau' -> 'Nassau'. Falls back to the slug."""
    name = re.sub(r'^how to play\s+(?:a |an |the )?', '', h1 or '', flags=re.I).strip()
    if not name:
        name = path.strip('/').split('/')[-1].replace('-', ' ').title()
    return name


def short_title(title):
    return re.sub(r'\s*[|—–-]\s*Halved\s*$', '', title or '').strip()


# --- Dates ------------------------------------------------------------------

def git_dates(rel):
    """(first-added, last-changed) for a file, or (None, None) without history."""
    def run(*args):
        try:
            out = subprocess.run(['git', '-C', ROOT, 'log', '--format=%ad',
                                  '--date=short', *args, '--', rel],
                                 capture_output=True, text=True, timeout=20).stdout.split()
            return out
        except (OSError, subprocess.SubprocessError):
            return []
    changed = run('-1')
    added = run('--diff-filter=A', '--follow')
    return (added[-1] if added else None), (changed[0] if changed else None)


def old_sitemap_dates():
    """The hand-kept lastmods from the sitemap this script replaces, so the
    first run keeps them instead of stamping every page with today."""
    try:
        xml = open(SITEMAP, encoding='utf-8').read()
    except OSError:
        return {}
    return dict(re.findall(r'<loc>([^<]+)</loc>\s*<lastmod>([^<]+)</lastmod>', xml))


def load_manifest():
    try:
        return json.load(open(MANIFEST, encoding='utf-8'))
    except (OSError, ValueError):
        return {}


def dates_for(rel, content, manifest, seeds, today):
    """Return (published, modified), updating the manifest entry in place.
    `modified` only moves when the page content (minus the SEO block) does."""
    digest = hashlib.sha256(strip_block(content).encode('utf-8')).hexdigest()[:16]
    entry = manifest.get(rel)
    if entry is None:
        # First sight of this page: the later of the old sitemap's hand-kept
        # date (under either URL form) and git's last change. The hand dates
        # ran stale — the homepage said 09-11 after a 09-27 edit.
        added, changed = git_dates(rel)
        seed = seeds.get(SITE + url_path(rel)) or seeds.get(SITE + '/' + rel)
        modified = max(filter(None, [seed, changed])) if (seed or changed) else today
        published = min(filter(None, [added, modified]))
        entry = {'hash': digest, 'published': published, 'modified': modified}
    elif entry.get('hash') != digest:
        entry = dict(entry, hash=digest, modified=today)
    manifest[rel] = entry
    return entry['published'], entry['modified']


# --- Building the head block ------------------------------------------------

def meta_tag(attr, key, value):
    return '<meta %s="%s" content="%s">' % (attr, key, html.escape(value, quote=True))


def ld_script(graph):
    doc = {'@context': 'https://schema.org', '@graph': graph}
    body = json.dumps(doc, indent=1, ensure_ascii=False).replace('</', '<\\/')
    return '<script type="application/ld+json">\n%s\n</script>' % body


def org_node():
    same = [APP_STORE_URL]
    if PLAY_PACKAGE:
        same.append('https://play.google.com/store/apps/details?id=' + PLAY_PACKAGE)
    return {'@type': 'Organization', '@id': ORG_ID, 'name': BRAND,
            'url': SITE + '/', 'email': CONTACT_EMAIL, 'sameAs': same}


def app_node(description):
    node = {'@type': 'MobileApplication', '@id': APP_ID, 'name': APP_NAME,
            'alternateName': BRAND,
            'operatingSystem': 'iOS, Android' if PLAY_PACKAGE else 'iOS',
            'applicationCategory': 'SportsApplication',
            'url': SITE + '/', 'downloadUrl': APP_STORE_URL,
            'image': OG_IMAGE, 'publisher': {'@id': ORG_ID},
            'offers': {'@type': 'Offer', 'price': '0', 'priceCurrency': 'USD'}}
    if description:
        node['description'] = description
    return node


def breadcrumbs(url, trail):
    return {'@type': 'BreadcrumbList', '@id': url + '#breadcrumb',
            'itemListElement': [
                {'@type': 'ListItem', 'position': i + 1, 'name': n, 'item': u}
                for i, (n, u) in enumerate(trail)]}


def build_block(rel, page, guides, published, modified):
    """The generated <head> block for one page. `page` is the parse of the
    page WITHOUT its old block, so it reflects only what the page declares."""
    path = url_path(rel)
    url = SITE + path
    kind = kind_of(path)
    title = page.title or BRAND
    desc = page.first('description') or DESCRIPTIONS.get(rel)
    lines = []

    if not page.links.get('canonical'):
        lines.append('<link rel="canonical" href="%s">' % url)
    if not page.first('description') and desc:
        lines.append(meta_tag('name', 'description', desc))
    if rel in NOINDEX and not page.noindex:
        lines.append(meta_tag('name', 'robots', 'noindex'))

    og = {'og:title': title,
          'og:description': desc,
          'og:url': url,
          'og:type': 'article' if kind == 'guide' else 'website',
          'og:site_name': BRAND,
          'og:image': OG_IMAGE}
    for key, value in og.items():
        if value and not page.first(key):
            lines.append(meta_tag('property', key, value))
    if not page.first('og:image'):
        lines += [meta_tag('property', 'og:image:width', '1200'),
                  meta_tag('property', 'og:image:height', '630'),
                  meta_tag('property', 'og:image:alt', OG_IMAGE_ALT)]
    if not page.first('twitter:card'):
        lines.append(meta_tag('name', 'twitter:card', 'summary_large_image'))
    if not page.first('twitter:image'):
        lines.append(meta_tag('name', 'twitter:image', OG_IMAGE))

    # iOS Safari's Smart App Banner: a native "Open / Get" bar for the listing.
    if not page.first('apple-itunes-app'):
        lines.append(meta_tag('name', 'apple-itunes-app', 'app-id=' + APP_STORE_ID))

    home_crumb = (BRAND, SITE + '/')
    hub_crumb = ('Game guides', SITE + '/games/')
    graph = None
    if kind == 'home':
        graph = [org_node(),
                 {'@type': 'WebSite', '@id': WEBSITE_ID, 'url': SITE + '/', 'name': BRAND,
                  'alternateName': APP_NAME, 'inLanguage': 'en-US',
                  'publisher': {'@id': ORG_ID}},
                 app_node(desc)]
    elif kind == 'hub':
        graph = [org_node(),
                 {'@type': 'CollectionPage', '@id': url, 'url': url,
                  'name': short_title(title), 'description': desc, 'inLanguage': 'en-US',
                  'isPartOf': {'@id': WEBSITE_ID}, 'publisher': {'@id': ORG_ID},
                  'breadcrumb': {'@id': url + '#breadcrumb'},
                  'mainEntity': {'@type': 'ItemList', 'itemListElement': [
                      {'@type': 'ListItem', 'position': i + 1, 'name': n, 'url': u}
                      for i, (n, u) in enumerate(guides)]}},
                 breadcrumbs(url, [home_crumb, hub_crumb])]
    elif kind == 'guide':
        name = game_name(page.h1[0] if page.h1 else '', path)
        graph = [org_node(),
                 {'@type': 'Article', '@id': url + '#article', 'url': url,
                  'mainEntityOfPage': url,
                  'headline': short_title(title)[:110],
                  'description': desc, 'image': page.first('og:image') or OG_IMAGE,
                  'inLanguage': 'en-US',
                  'datePublished': published, 'dateModified': modified,
                  'author': {'@id': ORG_ID}, 'publisher': {'@id': ORG_ID},
                  'about': {'@type': 'Thing', 'name': name + ' (golf game)'},
                  'breadcrumb': {'@id': url + '#breadcrumb'}},
                 breadcrumbs(url, [home_crumb, hub_crumb, (name, url)])]
    if graph:
        lines.append(ld_script(graph))

    return '\n'.join([BEGIN] + lines + [END])


def insert_block(text, block):
    text = strip_block(text)
    i = text.lower().find('</head>')
    if i == -1:
        raise ValueError('no </head>')
    return text[:i].rstrip('\n') + '\n' + block + '\n' + text[i:]


def build_sitemap(entries):
    rows = ''.join('  <url><loc>%s</loc><lastmod>%s</lastmod></url>\n' % (u, d)
                   for u, d in entries)
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<!-- Generated by build-seo.py from the pages on disk. Do not edit. -->\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            + rows + '</urlset>\n')


def sort_key(rel):
    path = url_path(rel)
    return ({'home': 0, 'hub': 1, 'guide': 2}.get(kind_of(path), 3), path)


# --- Audit ------------------------------------------------------------------

def resolve(page_path, href, files):
    """Classify an internal link. Returns (status, detail, target page or None)
    where status is 'ok', 'redirect', 'broken', or None for links that aren't
    internal (mail, anchors, other sites)."""
    if href.startswith(('mailto:', 'tel:', 'sms:', 'javascript:', '#', 'data:')):
        return None, None, None
    parts = urlsplit(urljoin(SITE + page_path, href))
    if parts.netloc not in ('halved.golf', 'www.halved.golf'):
        return None, None, None
    p = parts.path or '/'
    rel = p.lstrip('/')
    if p.endswith('/'):
        target = rel + 'index.html'
        return ('ok', p, target) if target in files else ('broken', p, None)
    if rel.endswith('.html'):
        if rel in files:
            return 'redirect', '%s → %s' % (p, url_path(rel)), rel
        return 'broken', p, None
    if rel in files:
        return 'ok', p, rel
    if rel + '.html' in files:
        return 'ok', p, rel + '.html'
    if rel + '/index.html' in files:
        return 'redirect', '%s → %s/' % (p, p), rel + '/index.html'
    if os.path.isfile(os.path.join(ROOT, rel)):
        return 'ok', p, None          # an asset: image, pdf, png…
    return 'broken', p, None


def audit(pages, sitemap_xml):
    """pages: {rel: final html}. Returns [(level, rel, message)]."""
    files = set(pages)
    found = []
    titles, descs, inbound = {}, {}, {rel: 0 for rel in pages}

    for rel, text in pages.items():
        path = url_path(rel)
        p = parse(text)
        err = lambda m: found.append(('error', rel, m))
        warn = lambda m: found.append(('warn', rel, m))

        if not p.title:
            err('no <title>')
        else:
            titles.setdefault(p.title, []).append(rel)
            if len(p.title) > TITLE_WARN:
                warn('title is %d chars; Google shows about %d: "%s"'
                     % (len(p.title), TITLE_WARN, p.title))
        desc = p.first('description')
        if not desc:
            err('no meta description')
        else:
            descs.setdefault(desc, []).append(rel)
            if not DESC_MIN <= len(desc) <= DESC_MAX:
                warn('description is %d chars (aim for %d–%d)' % (len(desc), DESC_MIN, DESC_MAX))

        canon = p.links.get('canonical', [])
        if len(canon) != 1:
            err('%d canonical links (want 1)' % len(canon))
        elif canon[0] != SITE + path:
            err('canonical %s but the page is served at %s' % (canon[0], SITE + path))
        for key in ('og:title', 'og:description', 'og:url', 'og:image'):
            if len(p.meta.get(key, [])) > 1:
                err('%s declared %d times' % (key, len(p.meta[key])))
        if p.first('og:url') and p.first('og:url') != SITE + path:
            err('og:url %s does not match %s' % (p.first('og:url'), SITE + path))

        if len(p.h1) != 1:
            err('%d <h1> elements (want 1)' % len(p.h1))
        for src, has_alt in p.imgs:
            if not has_alt:
                err('image without alt: %s' % src)

        for raw in p.ld:
            try:
                json.loads(raw)
            except ValueError as e:
                err('invalid JSON-LD: %s' % e)

        seen = set()
        for href in p.hrefs:
            status, detail, target = resolve(path, href, files)
            if status == 'broken':
                err('broken link: %s' % href)
            elif status == 'redirect' and detail not in seen:
                seen.add(detail)
                warn('link takes a redirect: %s' % detail)
            if target and target != rel:
                inbound[target] += 1

    for t, rels in titles.items():
        if len(rels) > 1:
            found.append(('error', ', '.join(rels), 'duplicate title "%s"' % t))
    for d, rels in descs.items():
        if len(rels) > 1:
            found.append(('warn', ', '.join(rels), 'duplicate description'))
    for rel, n in inbound.items():
        if n == 0 and rel != 'index.html' and rel not in NOINDEX:
            found.append(('warn', rel, 'no other page links here'))

    listed = set(re.findall(r'<loc>([^<]+)</loc>', sitemap_xml))
    for rel in pages:
        u = SITE + url_path(rel)
        if rel not in NOINDEX and u not in listed:
            found.append(('error', rel, 'missing from sitemap.xml'))
    return found


# --- Main -------------------------------------------------------------------

def main():
    check = '--check' in sys.argv[1:]
    today = datetime.date.today().isoformat()
    manifest = load_manifest()
    seeds = old_sitemap_dates() if not manifest else {}

    rels = sorted(find_pages(), key=sort_key)
    originals = {r: open(os.path.join(ROOT, r), encoding='utf-8').read() for r in rels}
    bare = {r: parse(strip_block(t)) for r, t in originals.items()}

    # The hub's guide list, in the order the hub itself presents them.
    guides, seen = [], set()
    hub = next((r for r in rels if kind_of(url_path(r)) == 'hub'), None)
    guide_rels = {url_path(r): r for r in rels if kind_of(url_path(r)) == 'guide'}
    order = [urlsplit(urljoin(SITE + '/games/', h)).path for h in (bare[hub].hrefs if hub else [])]
    for path in order + sorted(guide_rels):
        r = guide_rels.get(path)
        if r and path not in seen:
            seen.add(path)
            guides.append((game_name(bare[r].h1[0] if bare[r].h1 else '', path), SITE + path))

    built, sitemap_rows = {}, []
    for r in rels:
        published, modified = dates_for(r, originals[r], manifest, seeds, today)
        block = build_block(r, bare[r], guides, published, modified)
        built[r] = insert_block(originals[r], block)
        if r not in NOINDEX:
            sitemap_rows.append((SITE + url_path(r), modified))
    for gone in set(manifest) - set(rels):
        del manifest[gone]
    sitemap_xml = build_sitemap(sitemap_rows)
    manifest_json = json.dumps(dict(sorted(manifest.items())), indent=1) + '\n'

    outputs = {os.path.join(ROOT, r): t for r, t in built.items()}
    outputs[SITEMAP] = sitemap_xml
    outputs[MANIFEST] = manifest_json

    stale = []
    for f, text in outputs.items():
        try:
            current = open(f, encoding='utf-8').read()
        except OSError:
            current = None
        if current != text:
            stale.append(os.path.relpath(f, ROOT))
            if not check:
                open(f, 'w', encoding='utf-8').write(text)

    findings = audit(built, sitemap_xml)
    if check:
        # The manifest's only job is dates; a stale one is not a site problem
        # unless the pages themselves also changed.
        page_stale = [s for s in stale if s != 'seo-manifest.json']
        for s in page_stale:
            findings.insert(0, ('error', s, 'out of date — run ./build-seo.py'))
    else:
        print('updated %d file(s)%s' % (len(stale), (': ' + ', '.join(stale)) if stale else ''))

    errors = [f for f in findings if f[0] == 'error']
    warns = [f for f in findings if f[0] == 'warn']
    for level, rel, msg in errors + warns:
        print('%-5s  %-38s %s' % (level.upper(), rel, msg))
    print('\n%d page(s) · %d error(s) · %d warning(s)' % (len(rels), len(errors), len(warns)))
    return 1 if errors else 0


if __name__ == '__main__':
    sys.exit(main())
