"""
Django settings for my_golf_app project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Load .env file from the project root if it exists.
# Supports the common KEY=VALUE format without requiring python-dotenv.
_env_file = Path(__file__).resolve().parent.parent / '.env'
if _env_file.exists():
    for _line in _env_file.read_text().splitlines():
        _line = _line.strip()
        if _line and not _line.startswith('#') and '=' in _line:
            _k, _, _v = _line.partition('=')
            os.environ.setdefault(_k.strip(), _v.strip())

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Set SECRET_KEY in your environment or .env file for production.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-@6g-3**v^msz99%j4%tg!kij12ahcq(1rvag=ghj!&f)kl53v@',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG=True in .env for local development only.
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Comma-separated list of allowed hosts, e.g. "golf.lipkin.us,*.up.railway.app"
_allowed = os.environ.get('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(',') if h.strip()]

# CSRF trusted origins — required for Django admin and any POST requests over HTTPS
_csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(',') if o.strip()]
# Always trust our known domains regardless of env var
for _host in ALLOWED_HOSTS:
    if not _host.startswith('.'):
        _origin = f'https://{_host}'
        if _origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_origin)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
        # Third party
    'rest_framework',
    'rest_framework.authtoken',
    # Local
    # 'accounts' must come BEFORE every app that references
    # settings.AUTH_USER_MODEL, otherwise the swappable-dependency
    # resolution at migrate-time can't find the User table.
    'accounts',
    'core',
    'scoring',
    'games',
    'tournament',
    'api',
]

# Custom user model lives in the `accounts` app.  Every Player /
# Course / Tournament / Round / etc. is scoped to user.account so two
# users in different accounts see entirely separate data sets.
AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # serve static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Logs every 401 with path / IP / auth-header presence so we can
    # diagnose the intermittent client-side silent-logout bug.  See
    # api/middleware.py for the rationale.
    'api.middleware.AuthFailureLogger',
]

ROOT_URLCONF = 'my_golf_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_golf_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# In production (Railway), DATABASE_URL is injected automatically.
# For local dev, set DATABASE_URL in .env or fall back to the explicit config.

import dj_database_url as _dj_db

_database_url = os.environ.get('DATABASE_URL')
if _database_url:
    DATABASES = {'default': _dj_db.config(default=_database_url, conn_max_age=600)}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'golf_app_db'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'Paulgres'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# ---------------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------------

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # browsable API
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # IsAccountMember = authenticated AND user.account_id is not null.
        # All tenant-scoped endpoints inherit this; public / login views
        # override with [AllowAny] or [IsAuthenticated] as needed.
        'accounts.scoping.IsAccountMember',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
}

# ---------------------------------------------------------------------------
# GolfCourseAPI (golfcourseapi.com) — course data import
# ---------------------------------------------------------------------------
# Set GOLF_API_KEY in your environment (or .env file).
# The base URL can be overridden if the provider changes their API version.

GOLF_API_KEY      = os.environ.get('GOLF_API_KEY', '')
GOLF_API_BASE_URL = os.environ.get('GOLF_API_BASE_URL', 'https://api.golfcourseapi.com')

# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# Client version compatibility
# ---------------------------------------------------------------------------
# Bump SERVER_VERSION with each deploy.
# Bump CLIENT_MIN_VERSION only when a server change is incompatible with
# older clients — this will force users to update the app before they can
# continue.  Leave CLIENT_MIN_VERSION at the last compatible release to
# allow older clients to keep working.
SERVER_VERSION    = '1.5.0'
CLIENT_MIN_VERSION = '1.1.0'

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
# Logs appear in the terminal where you run `python manage.py runserver`.
# Set DJANGO_LOG_LEVEL=DEBUG in your .env to see full API response bodies.

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        # Our app code — show INFO and above (includes API response bodies,
        # import summaries, tee warnings, and errors).
        'api': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'services': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        # Django request logs — keep at WARNING to avoid noise.
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}


# ---------------------------------------------------------------------------
# Test runner: skip migrations
# ---------------------------------------------------------------------------
# Django's TestCase machinery normally rebuilds the schema by running every
# migration in order against an empty DB.  Some of our older migrations use
# raw SQL (RunSQL) to add columns and then assume those columns exist in
# Django's migration state — which only works against a DB that already has
# the column.  On a fresh test DB the AlterField operations fail.
#
# Skipping migrations and instead creating tables straight from the model
# definitions (Django's old syncdb behavior) is the standard workaround.
# Test DB shape matches the latest model state, which is what we actually
# want to test against.  Production DBs are unaffected.
import sys

class _DisableMigrations:
    def __contains__(self, item): return True
    def __getitem__(self, item):  return None

if 'test' in sys.argv:
    MIGRATION_MODULES = _DisableMigrations()
